allocate_particles_memory – SPHINCS_ID
allocate_particles_memory Module Procedure
202 statements
Source File
module procedure allocate_particles_memory module module subroutine allocate_particles_memory(this) Interface →
Allocate memory for the LORENE ID on the particles
FT 10.11.2020
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
Called by
Contents
None
Call graph
allocate_particles_memory calls allocate_particles_memory
construct_particles_std calls allocate_particles_memory, construct_particles_std
particles calls construct_particles_std
convergence_test calls particles
sphincs_id calls particles