allocate_bssn_fields – SPHINCS_LORENE
allocate_bssn_fields Module Procedure
GNU Free Documentation License
19 statements
Source File
module procedure allocate_bssn_fields module module subroutine allocate_bssn_fields(THIS) Interface →
Uses
mesh_refinement
Arguments
Type Intent Optional Attributes Name
class(bssn_id), intent(inout) :: THIS
Calls
Called by
Contents
None
Call graph
allocate_bssn_fields calls allocate_grid_function, allocate_bssn_fields
construct_bssn_id calls allocate_bssn_fields, construct_bssn_id
bssn_id calls construct_bssn_id
convergence_test calls bssn_id
sphincs_lorene_bns calls bssn_id