check_particle_positions – SPHINCS_LORENE
check_particle_positions Subroutine
GNU Free Documentation License
70 statements
Source File
public subroutine check_particle_positions(npart, pos, debug)
Uses
NR
Check that the particles are not at the same positions
FT 1.9.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(in), DIMENSION(3,npart) :: pos
logical, intent(in), optional :: debug
Calls
Called by
Contents
Variables
itr itr2 x_idx x_number x_sort
Source Code
check_particle_positions
Variables
Type Visibility Attributes Name Initial
integer, public :: itr
integer, public :: itr2
integer, public :: x_idx
integer, public, DIMENSION(:), ALLOCATABLE :: x_number
integer, public, DIMENSION(npart) :: x_sort
Source Code
  SUBROUTINE check_particle_positions( npart, pos, debug )
    !*************************************************
    !
    !# Check that the particles are not at the same
    !  positions
    !
    !  FT 1.9.2021
    !
    !*************************************************
    USE NR,             ONLY: indexx
    IMPLICIT NONE
    INTEGER, INTENT(IN):: npart
    LOGICAL, INTENT(IN), OPTIONAL:: debug
    DOUBLE PRECISION, DIMENSION(3,npart), INTENT(IN):: pos
    INTEGER:: itr, itr2, x_idx
    INTEGER, DIMENSION(npart):: x_sort
    INTEGER, DIMENSION(:), ALLOCATABLE:: x_number
    PRINT *, "** Checking that there are not multiple particles", &
             " at the same position..."
    PRINT *
    ALLOCATE( x_number( npart ) )
    ! Sort x coordinates of the particles
    CALL indexx( npart, pos( 1, : ), x_sort )
    x_number= 1
    itr2= 1
    ! Find the number of times each x appears
    DO itr= 1, npart - 1, 1
      IF( pos( 1, x_sort(itr) ) == &
          pos( 1, x_sort(itr+1) ) )THEN
        x_number(itr2)= x_number(itr2) + 1
      ELSE
        itr2= itr2 + 1
      ENDIF
    ENDDO
    x_number= x_number(1:itr2)
    IF( SUM( x_number ) /= npart )THEN
      PRINT *, "** ERROR! The sum of the numbers of particles with the same", &
               " x is not equal to the particle number."
      PRINT *, " * SUM( x_number )=", SUM( x_number ), ", ", &
               "npart=", npart
      PRINT *, " * Stopping..."
      PRINT *
      STOP
    ENDIF
    IF( PRESENT(debug) .AND. debug .EQV. .TRUE. )THEN
      !$OMP PARALLEL DO DEFAULT( NONE ) &
      !$OMP             SHARED( pos, x_sort, x_number ) &
      !$OMP             PRIVATE( itr, itr2, x_idx )
      DO itr= 1, SIZE(x_number), 1
        IF( itr == 1 )THEN
          x_idx= 1
        ELSE
          x_idx= SUM(x_number(1:itr-1)) + 1
        ENDIF
        DO itr2= x_idx, x_idx + x_number(itr) - 2, 1
          ! If they do not have the same x
          IF( pos( 1, x_sort(itr2) ) /= &
              pos( 1, x_sort(itr2+1) ) )THEN
            PRINT *, "** ERROR! ", "The two particles ", x_sort(itr2), &
                     " and", x_sort(itr2+1), &
                     " do not have the same x, but should!"
            PRINT *, pos( :, x_sort(itr2) )
            PRINT *, pos( :, x_sort(itr2+1) )
            PRINT *, " * Stopping..."
            PRINT *
            STOP
          ENDIF
        ENDDO
      ENDDO
      !$OMP END PARALLEL DO
    ENDIF
    !$OMP PARALLEL DO DEFAULT( NONE ) &
    !$OMP             SHARED( pos, x_sort, x_number ) &
    !$OMP             PRIVATE( itr, itr2, x_idx )
    DO itr= 1, SIZE(x_number), 1
      IF( itr == 1 )THEN
        x_idx= 1
      ELSE
        x_idx= SUM(x_number(1:itr-1)) + 1
      ENDIF
      DO itr2= x_idx, x_idx + x_number(itr) - 2, 1
        ! If they have the same y
        IF( pos( 2, x_sort(itr2) ) == &
            pos( 2, x_sort(itr2+1) ) )THEN
          ! If they have the same z
          IF( pos( 3, x_sort(itr2) ) == &
              pos( 3, x_sort(itr2+1) ) )THEN
            ! They are the same
            PRINT *, "** ERROR! ", "The two particles ", x_sort(itr2), &
                     " and", x_sort(itr2+1), " have the same coordinates!"
            PRINT *, pos( :, x_sort(itr2) )
            PRINT *, pos( :, x_sort(itr2+1) )
            PRINT *, " * Stopping..."
            PRINT *
            STOP
          ENDIF
        ENDIF
      ENDDO
    ENDDO
    !$OMP END PARALLEL DO
    DEALLOCATE( x_number )
  END SUBROUTINE check_particle_positions
Call graph
check_particle_positions calls indexx
construct_particles calls check_particle_positions, construct_particles
perform_apm calls check_particle_positions, perform_apm
particles calls construct_particles
convergence_test calls particles
sphincs_lorene_bns calls particles