compute_adm_momentum – SPHINCS_ID
compute_adm_momentum Module Procedure
80 statements
Source File
module procedure compute_adm_momentum module module subroutine compute_adm_momentum(this, npart, pos, nlrf, u, pr, vel_u, theta, nstar, nu, lapse, shift, adm_mom) Interface →
Uses
utility
metric_on_particles
deactivate_particles
constants
recovery
tensor
units
Computes an estimate of the linear momentum using the canonical momentum per baryon on the particles
Todo
add reference
FT 08.04.2022
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
integer, intent(in) :: npart
Particle number
double precision, intent(in), DIMENSION(3,npart) :: pos
Particle positions
double precision, intent(in), DIMENSION(npart) :: nlrf
Baryon density in the local rest frame on the particles
double precision, intent(in), DIMENSION(npart) :: u
Specific internal energy on the particles
double precision, intent(in), DIMENSION(npart) :: pr
Pressure on the particles
double precision, intent(in), DIMENSION(3,npart) :: vel_u
Spatial velocity in the computing frame on the particles
double precision, intent(in), DIMENSION(npart) :: theta
Generalized Lorentz factor on the particles
double precision, intent(in), DIMENSION(npart) :: nstar
Proper baryon density in the local rest frame on the particles
double precision, intent(in), DIMENSION(npart) :: nu
Baryon number per particle
double precision, intent(in), DIMENSION(npart) :: lapse
Lapse function on the particles
double precision, intent(in), DIMENSION(3,npart) :: shift
Shift vector on the particles
double precision, intent(out), DIMENSION(3) :: adm_mom
ADM linear momentum
Calls
Called by
Contents
Variables
a a_max debug det e_hat_rec exist finalnamefile i_mat i_matter j nlrf_rec nstar_rec p_max pr_rec s_l_rec shift_norm2 theta_rec u_rec unit_recovery vel_u_rec
Variables
Type Visibility Attributes Name Initial
integer, private :: a
integer, private :: a_max
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
double precision, private, DIMENSION(npart) :: e_hat_rec
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
character(len=2), private :: i_mat
integer, private :: i_matter
integer, private :: j
double precision, private, DIMENSION(npart) :: nlrf_rec
double precision, private, DIMENSION(npart) :: nstar_rec
double precision, private :: p_max
double precision, private, DIMENSION(npart) :: pr_rec
double precision, private, DIMENSION(3,npart) :: s_l_rec
double precision, private :: shift_norm2
double precision, private, DIMENSION(npart) :: theta_rec
double precision, private, DIMENSION(npart) :: u_rec
integer, private, parameter :: unit_recovery = 34956
double precision, private, DIMENSION(3,npart) :: vel_u_rec
Call graph
compute_adm_momentum calls phys_2_cons, theta_fb, compute_g4, deallocate_metric_on_particles, g4_ll, pr_fb, vel_u_fb, determinant_sym4x4, spatial_vector_norm_sym3x3, nlrf_fb, u_fb, allocate_metric_on_particles, cs_fb, compute_adm_momentum
compute_and_print_sph_variables calls compute_adm_momentum, compute_and_print_sph_variables