compute_and_print_bssn_constraints_grid – SPHINCS_ID
compute_and_print_bssn_constraints_grid Module Procedure
402 statements
Source File
module procedure compute_and_print_bssn_constraints_grid module module subroutine compute_and_print_bssn_constraints_grid(this, id, namefile, name_logfile) Interface →
Uses
constants
McLachlan_refine
matrix
utility
tensor
bns_fuka
mesh_refinement
Compute, store, analyze and print the BSSN constraints to a formatted file. The computation is done by importing the hydro ID on the gravity grid, without any information on the particles.
FT 1.02.2021
DEALLOCATE(u_coord) DEALLOCATE(u_coord_l)
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: this
bssn object to which this PROCEDURE is bound
class(idbase), intent(inout) :: id
idbase object used to read the hydrodynamical \(\mathrm{ID}\) to the mesh
character(len=*), intent(inout) :: namefile
character(len=*), intent(inout) :: name_logfile
Calls
Called by
Contents
Variables
HC_A HC_derphi HC_hand HC_rho HC_trK Tmunu_ll abs_grid baryon_density debug detg4 energy_density exist fd_lim finalname_logfile g4 g4temp i ig4 imax imin j k l lorentz_factor min_abs_y min_abs_z min_ix_y min_ix_z min_iy_y min_iy_z min_iz_y min_iz_z n_reflev name_analysis name_constraint pressure specific_energy u_euler_l u_euler_norm unit_logfile v_euler v_euler_l
Subroutines
compute_4velocity_eul compute_stress_energy
Variables
Type Visibility Attributes Name Initial
type(grid_function_scalar), private :: HC_A
type(grid_function_scalar), private :: HC_derphi
type(grid_function_scalar), private :: HC_hand
type(grid_function_scalar), private :: HC_rho
type(grid_function_scalar), private :: HC_trK
type(grid_function), private :: Tmunu_ll
double precision, private, DIMENSION(:, :, :, :), ALLOCATABLE :: abs_grid
type(grid_function_scalar), private :: baryon_density
logical, private, parameter :: debug = .FALSE.
double precision, private :: detg4
type(grid_function_scalar), private :: energy_density
logical, private :: exist
integer, private :: fd_lim
character(len=:), private, ALLOCATABLE :: finalname_logfile
type(grid_function), private :: g4
double precision, private, DIMENSION(4, 4) :: g4temp
integer, private :: i
double precision, private, DIMENSION(4, 4) :: ig4
integer, private, DIMENSION(3) :: imax
integer, private, DIMENSION(3) :: imin
integer, private :: j
integer, private :: k
integer, private :: l
type(grid_function_scalar), private :: lorentz_factor
double precision, private :: min_abs_y
double precision, private :: min_abs_z
integer, private :: min_ix_y
integer, private :: min_ix_z
integer, private :: min_iy_y
integer, private :: min_iy_z
integer, private :: min_iz_y
integer, private :: min_iz_z
character(len=2), private :: n_reflev
character(len=:), private, ALLOCATABLE :: name_analysis
character(len=:), private, ALLOCATABLE :: name_constraint
type(grid_function_scalar), private :: pressure
type(grid_function_scalar), private :: specific_energy
type(grid_function), private :: u_euler_l
double precision, private :: u_euler_norm = zero
integer, private :: unit_logfile
type(grid_function), private :: v_euler
type(grid_function), private :: v_euler_l
Subroutines
subroutine compute_4velocity_eul()
Compute the components of the fluid -velocity wrt the Eulerian observer See Sec.7.3 in Alcubierre, "Introduction to 3+1 Numerical Relativity"
FT 25.04.2022
Arguments
None
subroutine compute_stress_energy()
Compute the components of the stress-energy tensor
FT 25.04.2022
Arguments
None
Call graph
compute_and_print_bssn_constraints_grid calls phi, trk, compute_stress_energy, shift_u, levels, allocate_grid_function, a_bssn3_ll, k_phys3_ll, hc, compute_4velocity_eul, g_bssn3_ll, gamma_u, gc, mc, lapse, rho, s, bssn_constraint_terms_interior, compute_and_print_bssn_constraints_grid