compute_ricci – SPHINCS_ID
compute_ricci Module Procedure
40 statements
Source File
module procedure compute_ricci module module subroutine compute_ricci(THIS) Interface →
Uses
tensor
utility
mesh_refinement
Computes the Ricci tensor and the Ricci scalar on the mesh
FT 10.02.2022
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: THIS
bssn object to which this PROCEDURE is bound
Calls
Called by
Contents
Variables
imax imin l max_ricci min_lapse
Variables
Type Visibility Attributes Name Initial
integer, private, DIMENSION(3) :: imax
integer, private, DIMENSION(3) :: imin
integer, private :: l
double precision, private :: max_ricci
double precision, private :: min_lapse
Call graph
compute_ricci calls allocate_grid_function, bssn_ricci_interior, gamma_u, trk, levels, a_bssn3_ll, ricci_ll, phi, g_bssn3_ll, ricci_scalar, compute_ricci