compute_adm_momentum_fluid_m2p – SPHINCS_ID
compute_adm_momentum_fluid_m2p Module Procedure
122 statements
Source File
module procedure compute_adm_momentum_fluid_m2p module module subroutine compute_adm_momentum_fluid_m2p(this, parts, adm_mom) Interface →
Uses
tensor
ADM_refine
gradient
input_output
metric_on_particles
sph_variables
BSSN_refine
mesh_refinement
alive_flag
utility
McLachlan_refine
constants
units
Computes an estimate of the linear momentum using the \(\mathrm{SPH}\) fields on the particles
Todo
add reference
FT 12.04.2022
Arguments
Type Intent Optional Attributes Name
class(tpo), intent(in) :: this
tpo object which this PROCEDURE is a member of
class(particles), intent(in) :: parts
particles object used to map the metric from the mesh to the particles, and to call the recovery procedures
double precision, intent(out), DIMENSION(3) :: adm_mom
ADM linear momentum of the fluid computed using the metric mapped with the mesh-to-particle mapping
Calls
Called by
Contents
Variables
a adm_mom_i debug det exist finalnamefile g3 i_mat i_matter j l lapse_loc nlrf_loc nu_loc p_max pos pr_loc shift shift_norm2 theta_loc u_loc unit_recovery v_l v_u vel_loc
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private, DIMENSION(parts% get_n_matter(),3) :: adm_mom_i
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
double precision, private, DIMENSION(6) :: g3
character(len=2), private :: i_mat
integer, private :: i_matter
integer, private :: j
integer, private :: l
double precision, private :: lapse_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: nlrf_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_loc
double precision, private :: p_max
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos
double precision, private, DIMENSION(:), ALLOCATABLE :: pr_loc
double precision, private, DIMENSION(3) :: shift
double precision, private :: shift_norm2
double precision, private, DIMENSION(:), ALLOCATABLE :: theta_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: u_loc
integer, private, parameter :: unit_recovery = 34956
double precision, private, DIMENSION(0:3,parts% get_npart()) :: v_l
double precision, private, DIMENSION(0:3) :: v_u
double precision, private, DIMENSION(:,:), ALLOCATABLE :: vel_loc
Call graph
compute_adm_momentum_fluid_m2p calls deallocate_gradient, allocate_bssn, allocate_ztmp, set_units, deallocate_bssn, allocate_sph_memory, deallocate_sph_memory, compute_tpo_metric, levels, g4_ll, alive, allocate_gradient, read_options, spatial_vector_norm_sym3x3, allocate_metric_on_particles, deallocate_metric_on_particles, allocate_adm, deallocate_ztmp, lower_index_4vector, deallocate_grid_function, get_metric_on_particles, allocate_grid_function, deallocate_adm, compute_adm_momentum_fluid_m2p
compute_tpo_metric calls invert_3x3_matrix