compute_adm_momentum_fluid_fields – SPHINCS_ID
compute_adm_momentum_fluid_fields Module Procedure
35 statements
Source File
module procedure compute_adm_momentum_fluid_fields module module subroutine compute_adm_momentum_fluid_fields(npart, g_xx, g_xy, g_xz, g_yy, g_yz, g_zz, lapse, shift_x, shift_y, shift_z, nu, theta, nlrf, pr, u, vel_u, adm_mom) Interface →
Uses
utility
constants
tensor
Computes an estimate of the linear momentum using the \(\mathrm{SPH}\) fields on the particles
Todo
add reference
FT 12.04.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
Particle number
double precision, intent(in), DIMENSION(npart) :: g_xx
double precision, intent(in), DIMENSION(npart) :: g_xy
double precision, intent(in), DIMENSION(npart) :: g_xz
double precision, intent(in), DIMENSION(npart) :: g_yy
double precision, intent(in), DIMENSION(npart) :: g_yz
double precision, intent(in), DIMENSION(npart) :: g_zz
Spatial metric on the particles
double precision, intent(in), DIMENSION(npart) :: lapse
Lapse function on the particles
double precision, intent(in), DIMENSION(npart) :: shift_x
double precision, intent(in), DIMENSION(npart) :: shift_y
double precision, intent(in), DIMENSION(npart) :: shift_z
Shift vector on the particles
double precision, intent(in), DIMENSION(npart) :: nu
Baryon number per particle
double precision, intent(in), DIMENSION(npart) :: theta
Generalized Lorentz factor on the particles
double precision, intent(in), DIMENSION(npart) :: nlrf
Baryon density in the local rest frame on the particles
double precision, intent(in), DIMENSION(npart) :: pr
Pressure on the particles
double precision, intent(in), DIMENSION(npart) :: u
Specific internal energy on the particles
double precision, intent(in), DIMENSION(3,npart) :: vel_u
Spatial velocity in the computing frame on the particles
double precision, intent(out), DIMENSION(3) :: adm_mom
ADM linear momentum
Calls
Called by
Contents
Variables
a debug det g4 j shift_norm2 unit_recovery v_l v_u
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
double precision, private, DIMENSION(n_sym4x4,npart) :: g4
integer, private :: j
double precision, private :: shift_norm2
integer, private, parameter :: unit_recovery = 34956
double precision, private, DIMENSION(0:3,npart) :: v_l
double precision, private, DIMENSION(0:3) :: v_u
Call graph
compute_adm_momentum_fluid_fields calls lower_index_4vector, determinant_sym4x4, spatial_vector_norm_sym3x3, compute_g4, compute_adm_momentum_fluid_fields
compute_adm_momentum_fluid calls compute_adm_momentum_fluid_fields
compute_and_print_sph_variables calls compute_adm_momentum_fluid_fields, compute_and_print_sph_variables