compute_and_print_bssn_constraints_particles – SPHINCS_ID
compute_and_print_bssn_constraints_particles Module Procedure
414 statements
Source File
module procedure compute_and_print_bssn_constraints_particles module module subroutine compute_and_print_bssn_constraints_particles(this, parts_obj, namefile, name_logfile) Interface →
Uses
units
Tmunu_refine
ADM_refine
map_particles_2_grid
RCB_tree_3D
particle_mesh_hash
tensor
BSSN_refine
mesh_refinement
gradient
kernel_table
McLachlan_refine
sph_variables
GravityAcceleration_refine
metric_on_particles
options
sphincs_sph
input_output
set_h
alive_flag
Compute, store and print the BSSN constraints to a formatted file. The computaton is done mapping the physical metric from the gravity to the particles, computing e stress-energy tensor on the particles, and mapping it to the gravity grid.
Todo
use the SPH density to compute the stress-energy tensor, rather than the density from the \(\mathrm{ID}\)
FT 1.02.2021
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: this
bssn object to which this PROCEDURE is bound
class(particles), intent(inout) :: parts_obj
particles object used to map the hydrodynamical \(\mathrm{ID}\) to the mesh
character(len=*), intent(inout) :: namefile
character(len=*), intent(inout) :: name_logfile
Calls
Called by
Contents
Variables
a abs_grid allocation_status counter debug exist finalname_logfile i imax imin j k l min_abs_y min_abs_z min_ix_y min_ix_z min_iy_y min_iy_z min_iz_y min_iz_z n_reflev name_analysis name_constraint nlrf_loc nu_loc pos_loc pressure_loc sph_density theta_loc u_loc unit_logfile vel_loc
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private, DIMENSION(:, :, :, :), ALLOCATABLE :: abs_grid
integer, private :: allocation_status
integer, private, SAVE :: counter = 1
logical, private, parameter :: debug = .FALSE.
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalname_logfile
integer, private :: i
integer, private, DIMENSION(3) :: imax
integer, private, DIMENSION(3) :: imin
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private :: min_abs_y
double precision, private :: min_abs_z
integer, private :: min_ix_y
integer, private :: min_ix_z
integer, private :: min_iy_y
integer, private :: min_iy_z
integer, private :: min_iz_y
integer, private :: min_iz_z
character(len=2), private :: n_reflev
character(len=:), private, ALLOCATABLE :: name_analysis
character(len=:), private, ALLOCATABLE :: name_constraint
double precision, private, DIMENSION(:), ALLOCATABLE :: nlrf_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_loc
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: pressure_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: sph_density
double precision, private, DIMENSION(:), ALLOCATABLE :: theta_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: u_loc
integer, private :: unit_logfile
double precision, private, DIMENSION(:,:), ALLOCATABLE :: vel_loc
Call graph
compute_and_print_bssn_constraints_particles calls hc_parts, mc_parts, gamma_u, deallocate_grid_function, allocate_rcb_tree_memory_3d, deallocate_metric_on_particles, deallocate_ztmp, read_options, exact_nei_tree_update, levels, allocate_sph_memory, allocate_metric_on_particles, deallocate_hash_memory, trk, allocate_gradient, deallocate_bssn, allocate_adm, g_bssn3_ll, set_units, lapse, allocate_grid_function, a_bssn3_ll, allocate_ztmp, deallocate_rcb_tree_memory_3d, deallocate_gravityacceleration, rho_parts, deallocate_gradient, deallocate_tmunu, allocate_gravityacceleration, map_2_grid_hash, s_parts, iorig, allocate_bssn, allocate_tmunu, gc_parts, deallocate_sph_memory, get_metric_on_particles, deallocate_adm, shift_u, alive, bssn_constraint_terms_interior, k_phys3_ll, phi, compute_and_print_bssn_constraints_particles