compute_and_export_bssn_constraints_particles – SPHINCS_ID
compute_and_export_bssn_constraints_particles Module Procedure
414 statements
Source File
module procedure compute_and_export_bssn_constraints_particles module module subroutine compute_and_export_bssn_constraints_particles(THIS, parts_obj, namefile, name_logfile) Interface →
Uses
GravityAcceleration_refine
metric_on_particles
set_h
particle_mesh_hash
mesh_refinement
alive_flag
tensor
gradient
McLachlan_refine
ADM_refine
kernel_table
units
sphincs_sph
RCB_tree_3D
BSSN_refine
options
Tmunu_refine
sph_variables
map_particles_2_grid
input_output
Compute, store and print the BSSN constraints to a formatted file. The computaton is done mapping the physical metric from the gravity to the particles, computing e stress-energy tensor on the particles, and mapping it to the gravity grid.
Todo
use the SPH density to compute the stress-energy tensor, rather than the density from the \(\mathrm{ID}\)
FT 1.02.2021
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: THIS
bssn object to which this PROCEDURE is bound
class(particles), intent(inout) :: parts_obj
particles object used to map the hydrodynamical \(\mathrm{ID}\) to the mesh
character(len=*), intent(inout) :: namefile
character(len=*), intent(inout) :: name_logfile
Calls
Called by
Contents
Variables
a abs_grid allocation_status counter debug exist finalname_logfile i imax imin j k l min_abs_y min_abs_z min_ix_y min_ix_z min_iy_y min_iy_z min_iz_y min_iz_z n_reflev name_analysis name_constraint nlrf_loc nu_loc pos_loc pressure_loc sph_density theta_loc u_loc unit_logfile vel_loc
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private, DIMENSION(:, :, :, :), ALLOCATABLE :: abs_grid
integer, private :: allocation_status
integer, private, SAVE :: counter = 1
logical, private, parameter :: debug = .FALSE.
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalname_logfile
integer, private :: i
integer, private, DIMENSION(3) :: imax
integer, private, DIMENSION(3) :: imin
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private :: min_abs_y
double precision, private :: min_abs_z
integer, private :: min_ix_y
integer, private :: min_ix_z
integer, private :: min_iy_y
integer, private :: min_iy_z
integer, private :: min_iz_y
integer, private :: min_iz_z
character(len=2), private :: n_reflev
character(len=:), private, ALLOCATABLE :: name_analysis
character(len=:), private, ALLOCATABLE :: name_constraint
double precision, private, DIMENSION(:), ALLOCATABLE :: nlrf_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_loc
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: pressure_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: sph_density
double precision, private, DIMENSION(:), ALLOCATABLE :: theta_loc
double precision, private, DIMENSION(:), ALLOCATABLE :: u_loc
integer, private :: unit_logfile
double precision, private, DIMENSION(:,:), ALLOCATABLE :: vel_loc
Call graph
compute_and_export_bssn_constraints_particles calls alive, read_options, deallocate_metric_on_particles, bssn_constraint_terms_interior, get_metric_on_particles, gc_parts, mc_parts, deallocate_gravityacceleration, iorig, deallocate_grid_function, rho_parts, deallocate_gradient, set_units, shift_u, allocate_metric_on_particles, deallocate_hash_memory, k_phys3_ll, levels, allocate_tmunu, exact_nei_tree_update, deallocate_sph_memory, allocate_grid_function, trk, allocate_rcb_tree_memory_3d, lapse, allocate_bssn, deallocate_tmunu, map_2_grid_hash, allocate_adm, phi, gamma_u, allocate_gravityacceleration, deallocate_ztmp, allocate_ztmp, deallocate_adm, allocate_gradient, deallocate_rcb_tree_memory_3d, hc_parts, allocate_sph_memory, deallocate_bssn, g_bssn3_ll, a_bssn3_ll, s_parts, compute_and_export_bssn_constraints_particles