compute_and_export_bssn_variables – SPHINCS_ID
compute_and_export_bssn_variables Module Procedure
69 statements
Source File
module procedure compute_and_export_bssn_variables module module subroutine compute_and_export_bssn_variables(THIS, namefile) Interface →
Uses
BSSN_refine
McLachlan_refine
ADM_refine
Tmunu_refine
GravityAcceleration_refine
mesh_refinement
Compute, stores and prints the BSSN variables to a binary file to be read by the evolution code SPHINCS_BSSN
FT 23.10.2020
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: THIS
bssn object to which this PROCEDURE is bound
character(len=*), intent(inout), optional :: namefile
Calls
Called by
Contents
Variables
call_flag l
Variables
Type Visibility Attributes Name Initial
integer, private, SAVE :: call_flag = 0
integer, private :: l
Call graph
compute_and_export_bssn_variables calls allocate_ztmp, deallocate_ztmp, deallocate_gravityacceleration, allocate_grid_function, deallocate_bssn, allocate_tmunu, adm_to_bssn, deallocate_grid_function, allocate_gravityacceleration, levels, allocate_bssn, allocate_adm, deallocate_tmunu, allocate_bssn_fields, write_bssn_dump, deallocate_adm, compute_and_export_bssn_variables
allocate_bssn_fields calls allocate_bssn_fields, allocate_grid_function