compute_and_print_sph_variables – SPHINCS_ID
compute_and_print_sph_variables Module Procedure
454 statements
Source File
module procedure compute_and_print_sph_variables module module subroutine compute_and_print_sph_variables(this, namefile) Interface →
Uses
gradient
tensor
kernel_table
alive_flag
units
sph_variables
APM
matrix
input_output
pwp_EOS
set_h
metric_on_particles
RCB_tree_3D
sphincs_sph
utility
NR
options
constants
analyze
Compute the \(\mathrm{SPH}\) variables from the \(\mathrm{ID}\), and print them to a binary file to be read by \(\texttt{SPHINCS_BSSN}\), and to a formatted file
FT 18.09.2020
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
character(len=*), intent(inout), optional :: namefile
Name of the formatted file where the SPH ID is printed to
Calls
Called by
Contents
Variables
Theta_a a call_flag cnt1 com_d_1pn com_d_newt com_x_1pn com_x_newt com_y_1pn com_y_newt com_z_1pn com_z_newt compose_namefile debug det few_ncand finalnamefile find_h_bruteforce_timer g4 gg4 i_mat i_matter ill itot l mass_1pn mass_newt mus n_problematic_h nus pnorm pnorm_newt pwp_gamma pwp_kappa px px_newt py py_newt pz pz_newt sq_detg4 sq_g tmp
Variables
Type Visibility Attributes Name Initial
double precision, private :: Theta_a
integer, private :: a
integer, private, SAVE :: call_flag = 0
integer, private :: cnt1
double precision, private :: com_d_1pn
double precision, private :: com_d_newt
double precision, private :: com_x_1pn
double precision, private :: com_x_newt
double precision, private :: com_y_1pn
double precision, private :: com_y_newt
double precision, private :: com_z_1pn
double precision, private :: com_z_newt
character(len=:), private, ALLOCATABLE :: compose_namefile
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
logical, private :: few_ncand
character(len=:), private, ALLOCATABLE :: finalnamefile
type(timer), private :: find_h_bruteforce_timer
double precision, private :: g4(n_sym4x4)
double precision, private :: gg4(n_sym4x4,this%npart)
character(len=2), private :: i_mat
integer, private :: i_matter
integer, private :: ill
integer, private :: itot
integer, private :: l
double precision, private :: mass_1pn
double precision, private :: mass_newt
integer, private :: mus
integer, private :: n_problematic_h
integer, private :: nus
double precision, private :: pnorm
double precision, private :: pnorm_newt
integer, private :: pwp_gamma
integer, private :: pwp_kappa
double precision, private :: px
double precision, private :: px_newt
double precision, private :: py
double precision, private :: py_newt
double precision, private :: pz
double precision, private :: pz_newt
double precision, private :: sq_detg4(this%npart)
double precision, private :: sq_g
double precision, private :: tmp
Call graph
compute_and_print_sph_variables calls deallocate_gradient, pos_u, rpart, read_options, compute_g4, allocate_gradient, deallocate_metric_on_particles, density, exact_nei_tree_update, determinant_sym4x4, select_eos_parameters, find_h_backup, gen_pwp_eos, nlrf, nic, assign_h, vel_u, theta, h, compute_adm_momentum, density_loop, ncand, set_units, timer, nu, cs, allocate_rcb_tree_memory_3d, lpart, pr, allocate_metric_on_particles, write_sphincs_dump, deallocate_rcb_tree_memory_3d, iorig, allocate_sph_memory, gen_pwp_cold_eos, u, shorten_eos_name, sq_det_g4, deallocate_sph_memory, spacetime_vector_norm_sym4x4, compute_and_print_sph_variables
compute_adm_momentum calls compute_adm_momentum, compute_g4, deallocate_metric_on_particles, determinant_sym4x4, allocate_metric_on_particles, phys_2_cons, theta_fb, g4_ll, pr_fb, vel_u_fb, spatial_vector_norm_sym3x3, nlrf_fb, u_fb, cs_fb