compute_and_export_SPH_variables – SPHINCS_LORENE
compute_and_export_SPH_variables Module Procedure
GNU Free Documentation License
440 statements
Source File
module procedure compute_and_export_SPH_variables module module subroutine compute_and_export_SPH_variables(THIS, namefile) Interface →
Uses
matrix
constants
RCB_tree_3D
APM
options
alive_flag
pwp_EOS
input_output
gradient
kernel_table
metric_on_particles
units
set_h
NR
sphincs_sph
sph_variables
Compute the SPH quantities from the LORENE ID, and export it to a binary file with write_SPHINCS_dump, and to a formatted file
FT 18.09.2020
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: THIS
particles object which this PROCEDURE is a member of
character(len=*), intent(inout), optional :: namefile
Name of the formatted file where the SPH ID is printed to
Calls
Called by
Contents
Variables
Theta_a a call_flag cnt1 compose_namefile debug det few_ncand finalnamefile g4 good_h i_matter itr2 max_it_h mus nus sq_g
Variables
Type Visibility Attributes Name Initial
double precision, private :: Theta_a
integer, private :: a
integer, private, SAVE :: call_flag = 0
integer, private :: cnt1
character(len=:), private, ALLOCATABLE :: compose_namefile
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
logical, private :: few_ncand
character(len=:), private, ALLOCATABLE :: finalnamefile
double precision, private :: g4(0:3,0:3)
logical, private :: good_h
integer, private :: i_matter
integer, private :: itr2
integer, private, parameter :: max_it_h = 1
integer, private :: mus
integer, private :: nus
double precision, private :: sq_g
Call graph
compute_and_export_sph_variables calls vel_u, iorig, nu, allocate_metric_on_particles, gen_pwp_eos_all, deallocate_metric_on_particles, allocate_rcb_tree_memory_3d, pos_u, sq_det_g4, nlrf, read_options, select_eos_parameters, pr, density, av, u, assign_h, allocate_gradient, set_units, deallocate_rcb_tree_memory_3d, write_sphincs_dump, get_u_pwp, ncand, allocate_sph_memory, divv, shorten_eos_name, determinant_4x4_matrix, temp, theta, deallocate_gradient, h, deallocate_sph_memory, density_loop, exact_nei_tree_update, compute_and_export_sph_variables