compute_adm_momentum_fluid_canmom – SPHINCS_ID
compute_adm_momentum_fluid_canmom Module Procedure
20 statements
Source File
module procedure compute_adm_momentum_fluid_canmom module module subroutine compute_adm_momentum_fluid_canmom(npart, g3, lapse, shift, nu, s_l, adm_mom) Interface →
Uses
tensor
constants
utility
Computes an estimate of the linear momentum using the canonical momentum per baryon on the particles
Todo
add reference
FT 08.04.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
Particle number
double precision, intent(in), DIMENSION(6,npart) :: g3
Spatial metric on the particles
double precision, intent(in), DIMENSION(npart) :: lapse
Lapse function on the particles
double precision, intent(in), DIMENSION(3,npart) :: shift
Shift vector on the particles
double precision, intent(in), DIMENSION(npart) :: nu
Baryon number per particle
double precision, intent(in), DIMENSION(3,npart) :: s_l
Canonical momentum per baryon on the particles
double precision, intent(out), DIMENSION(3) :: adm_mom
ADM linear momentum
Calls
Called by
Contents
Variables
a debug det j shift_norm2 unit_recovery
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
integer, private :: j
double precision, private :: shift_norm2
integer, private, parameter :: unit_recovery = 34956
Call graph
compute_adm_momentum_fluid_canmom calls spatial_vector_norm_sym3x3, compute_adm_momentum_fluid_canmom
compute_adm_momentum_fluid calls compute_adm_momentum_fluid_canmom