compute_and_print_bssn_variables – SPHINCS_ID
compute_and_print_bssn_variables Module Procedure
203 statements
Source File
module procedure compute_and_print_bssn_variables module module subroutine compute_and_print_bssn_variables(this, namefile) Interface →
Uses
GravityAcceleration_refine
BSSN_refine
McLachlan_refine
Tmunu_refine
mesh_refinement
tensor
ADM_refine
utility
Compute, stores and prints the BSSN variables to a binary file to be read by the evolution code SPHINCS_BSSN
Note
Tested with 7 301**3 refinement levels on 05.07.2022. No memory issues.
Created: FT 23.10.2020 Last updated: FT 05.07.2022
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: this
bssn object to which this PROCEDURE is bound
character(len=*), intent(inout), optional :: namefile
Calls
Called by
Contents
Variables
call_flag dt_lapse dt_shift_u i j k l
Subroutines
check_bssn_id_for_NaNs
Variables
Type Visibility Attributes Name Initial
integer, private, SAVE :: call_flag = 0
type(grid_function_scalar), private :: dt_lapse
type(grid_function), private :: dt_shift_u
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: l
Subroutines
subroutine check_bssn_id_for_NaNs()
Search the \(\mathrm{BSSNOK}\) fields for NaNs, and STOP if one NaN is found, printing an informative message to the standard output.
Created: FT 05.07.2022 Last updated: FT 05.07.2022
Arguments
None
Call graph
compute_and_print_bssn_variables calls deallocate_gravityacceleration, write_bssn_dump, deallocate_bssn, deallocate_ztmp, levels, allocate_tmunu, standard_tpo_to_bssn, deallocate_tmunu, allocate_bssn_fields, deallocate_grid_function, allocate_bssn, allocate_ztmp, allocate_gravityacceleration, allocate_grid_function, check_bssn_id_for_nans, compute_and_print_bssn_variables
standard_tpo_to_bssn calls adm_to_bssn_interior, adm_to_bssn_everywhere
allocate_bssn_fields calls allocate_bssn_fields, allocate_grid_function