compute_g4 – SPHINCS_ID
compute_g4 Subroutine
GNU Free Documentation License
19 statements
Source File
public subroutine compute_g4(ix, iy, iz, lapse, shift_u, g_phys3_ll, g4)
Uses
tensor
Arguments
Type Intent Optional Attributes Name
integer :: ix
integer :: iy
integer :: iz
double precision, intent(inout), DIMENSION(:,:,:) :: lapse
double precision, intent(inout), DIMENSION(:,:,:,:) :: shift_u
double precision, intent(inout), DIMENSION(:,:,:,:) :: g_phys3_ll
double precision, intent(inout), DIMENSION(:,:,:,:) :: g4
Called by
Contents
Source Code
compute_g4
Source Code
  SUBROUTINE compute_g4( ix, iy, iz, lapse, shift_u, g_phys3_ll, g4 )
    !************************************************
    !                                               *
    ! Computes the spacetime metric from lapse,     *
    ! shift and spatial metric
    !                                               *
    ! FT 27.11.2020                                 *
    !                                               *
    !************************************************
    USE tensor,     ONLY: itt, itx, ity, itz, ixx, ixy, &
                          ixz, iyy, iyz, izz, jxx, jxy, jxz, &
                          jyy, jyz, jzz, jx, jy, jz, n_sym3x3, n_sym4x4
    IMPLICIT NONE
    INTEGER:: ix, iy, iz
    DOUBLE PRECISION, DIMENSION(:,:,:), INTENT( IN OUT ):: &
    lapse
    DOUBLE PRECISION, DIMENSION(:,:,:,:), INTENT( IN OUT ):: &
    shift_u
    DOUBLE PRECISION, DIMENSION(:,:,:,:), INTENT( IN OUT ):: &
    g_phys3_ll
    DOUBLE PRECISION, DIMENSION(:,:,:,:), INTENT( IN OUT ):: g4
    g4(ix,iy,iz,itt)= - lapse(ix,iy,iz)*lapse(ix,iy,iz) &
                      + g_phys3_ll(ix,iy,iz,jxx) &
                       *shift_u(ix,iy,iz,jx) &
                       *shift_u(ix,iy,iz,jx) &
                      + 2.0D0*g_phys3_ll(ix,iy,iz,jxy) &
                       *shift_u(ix,iy,iz,jx) &
                       *shift_u(ix,iy,iz,jy) &
                      + 2.0D0*g_phys3_ll(ix,iy,iz,jxz) &
                       *shift_u(ix,iy,iz,jx) &
                       *shift_u(ix,iy,iz,jz) &
                      + g_phys3_ll(ix,iy,iz,jyy) &
                       *shift_u(ix,iy,iz,jy) &
                       *shift_u(ix,iy,iz,jy) &
                      + 2.0D0*g_phys3_ll(ix,iy,iz,jyz) &
                       *shift_u(ix,iy,iz,jy) &
                       *shift_u(ix,iy,iz,jz) &
                      + g_phys3_ll(ix,iy,iz,jzz) &
                       *shift_u(ix,iy,iz,jz) &
                       *shift_u(ix,iy,iz,jz)
    g4(ix,iy,iz,itx)=   g_phys3_ll(ix,iy,iz,jxx)*shift_u(ix,iy,iz,jx) &
                      + g_phys3_ll(ix,iy,iz,jxy)*shift_u(ix,iy,iz,jy) &
                      + g_phys3_ll(ix,iy,iz,jxz)*shift_u(ix,iy,iz,jz)
    g4(ix,iy,iz,ity)=   g_phys3_ll(ix,iy,iz,jxy)*shift_u(ix,iy,iz,jx) &
                      + g_phys3_ll(ix,iy,iz,jyy)*shift_u(ix,iy,iz,jy) &
                      + g_phys3_ll(ix,iy,iz,jyz)*shift_u(ix,iy,iz,jz)
    g4(ix,iy,iz,itz)=   g_phys3_ll(ix,iy,iz,jxz)*shift_u(ix,iy,iz,jx) &
                      + g_phys3_ll(ix,iy,iz,jyz)*shift_u(ix,iy,iz,jy) &
                      + g_phys3_ll(ix,iy,iz,jzz)*shift_u(ix,iy,iz,jz)
    g4(ix,iy,iz,ixx)= g_phys3_ll(ix,iy,iz,jxx)
    g4(ix,iy,iz,ixy)= g_phys3_ll(ix,iy,iz,jxy)
    g4(ix,iy,iz,ixz)= g_phys3_ll(ix,iy,iz,jxz)
    g4(ix,iy,iz,iyy)= g_phys3_ll(ix,iy,iz,jyy)
    g4(ix,iy,iz,iyz)= g_phys3_ll(ix,iy,iz,jyz)
    g4(ix,iy,iz,izz)= g_phys3_ll(ix,iy,iz,jzz)
  END SUBROUTINE compute_g4
Call graph
import_id_spacetime calls compute_g4, import_id_spacetime
compute_and_export_bssn_constraints_grid calls compute_g4, compute_and_export_bssn_constraints_grid