construct_particles – SPHINCS_ID
construct_particles Module Procedure
GNU Free Documentation License
610 statements
Source File
module procedure construct_particles module module function construct_particles(id, dist) result(parts) Interface →
Uses
alive_flag
options
kernel_table
tensor
units
constants
NR
input_output
The constructor performs all the tasks needed to set up the particle distribution with the \(\texttt{LORENE}\) ID on it. It calls all the PROCEDURES that rely on an object of TYPE bns.
Todo
assign sub-tasks to separate SUBROUTINES CONTAINED in this SUBMODULE
FT 17.10.2020
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: id
idbase object representing the BNS for which we want to place particles
integer, intent(in) :: dist
Identifier of the desired particle distribution:
0: Read particle positions (and optionally the baryon number per particle) from a formatted file
1: Place particles on a single lattice that surrounds both stars
2: Place particles on two lattices, each one surrounding a star
3: Place particles on spherical surfaces inside the stars
Warning
Method 1 is almost deprecated, since method 2 is effectively an improvement of method 1
Return Value type(particles)
Constructed particles object
Calls
Called by
Contents
Variables
a apm_iterate apm_max_it barycenter center central_density column_nu columns compose_eos compose_filename compose_path correct_nu counter debug exist file_exists filename_apm_pos filename_apm_pos_id filename_apm_results filename_mass_profile filename_shells_pos filename_shells_radii header_lines i_matter last_r lower_bound lower_factor mass_it max_inc max_length max_mass max_steps n_cols n_matter_tmp nlines npart_des npart_des_i npart_i_tmp npart_tmp nu_ratio_des nuratio_des nuratio_thres nx_gh ny_gh nz_gh parts_all parts_pos parts_pos_namefile parts_pos_path pvol_tmp randomize_phi randomize_r randomize_theta read_nu redistribute_nu reflect_particles_x sizes str_i stretch thres tmp_pos total_mass unit_pos upper_bound upper_factor use_thres xmax xmin ymax ymin zmax zmin
Derived Types
parts_i
Functions
check_negative_hydro import_density
Subroutines
compute_nstar_p get_nstar_p import_id integrate_mass_density
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, DIMENSION(id% get_n_matter()) :: apm_iterate
integer, private :: apm_max_it
double precision, private, DIMENSION(id% get_n_matter(),3) :: barycenter
double precision, private, DIMENSION(id% get_n_matter(),3) :: center
double precision, private, DIMENSION(id% get_n_matter()) :: central_density
integer, private :: column_nu
integer, private, DIMENSION(3) :: columns
logical, private :: compose_eos
character(len=max_length), private :: compose_filename
character(len=max_length), private :: compose_path
logical, private :: correct_nu
integer, private, SAVE :: counter = 1
logical, private, parameter :: debug = .FALSE.
logical, private :: exist
logical, private :: file_exists
character(len=max_length), private :: filename_apm_pos
character(len=max_length), private :: filename_apm_pos_id
character(len=max_length), private :: filename_apm_results
character(len=max_length), private :: filename_mass_profile
character(len=max_length), private :: filename_shells_pos
character(len=max_length), private :: filename_shells_radii
integer, private :: header_lines
integer, private :: i_matter
double precision, private :: last_r
double precision, private :: lower_bound
double precision, private :: lower_factor
logical, private :: mass_it
integer, private :: max_inc
integer, private, parameter :: max_length = 50
double precision, private :: max_mass
integer, private :: max_steps
integer, private :: n_cols
integer, private :: n_matter_tmp
integer, private :: nlines
integer, private :: npart_des
integer, private, DIMENSION(id% get_n_matter()) :: npart_des_i
integer, private, DIMENSION(id% get_n_matter()) :: npart_i_tmp
integer, private :: npart_tmp
double precision, private :: nu_ratio_des
double precision, private :: nuratio_des
double precision, private :: nuratio_thres
integer, private :: nx_gh
integer, private :: ny_gh
integer, private :: nz_gh
type(parts_i), private, DIMENSION(id% get_n_matter()) :: parts_all
character(len=max_length), private :: parts_pos
character(len=:), private, ALLOCATABLE :: parts_pos_namefile
character(len=max_length), private :: parts_pos_path
double precision, private :: pvol_tmp
logical, private :: randomize_phi
logical, private :: randomize_r
logical, private :: randomize_theta
logical, private :: read_nu
logical, private :: redistribute_nu
logical, private :: reflect_particles_x
double precision, private, DIMENSION(id% get_n_matter(),6) :: sizes
character(len=3), private :: str_i
double precision, private :: stretch
double precision, private :: thres
double precision, private, DIMENSION(:, :), ALLOCATABLE :: tmp_pos
double precision, private :: total_mass
integer, private, parameter :: unit_pos = 2289
double precision, private :: upper_bound
double precision, private :: upper_factor
logical, private :: use_thres
double precision, private :: xmax
double precision, private :: xmin
double precision, private :: ymax
double precision, private :: ymin
double precision, private :: zmax
double precision, private :: zmin
Derived Types
type :: parts_i
Components
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:), ALLOCATABLE :: pmass_i
double precision, private, DIMENSION(:, :), ALLOCATABLE :: pos_i
double precision, private, DIMENSION(:), ALLOCATABLE :: pvol_i
Functions
function check_negative_hydro(x, y, z) result(answer)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value integer
function import_density(x, y, z) result(density)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value double precision
Subroutines
subroutine compute_nstar_p(npart_real, lapse, shift_x, shift_y, shift_z, v_euler_x, v_euler_y, v_euler_z, g_xx, g_xy, g_xz, g_yy, g_yz, g_zz, baryon_density, nstar_p)
Compute nstar_p, the proper baryon mass density, given the \(\texttt{LORENE}\) ID
FT 31.08.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
double precision, intent(in), DIMENSION(npart_real) :: lapse
double precision, intent(in), DIMENSION(npart_real) :: shift_x
double precision, intent(in), DIMENSION(npart_real) :: shift_y
double precision, intent(in), DIMENSION(npart_real) :: shift_z
double precision, intent(in), DIMENSION(npart_real) :: v_euler_x
double precision, intent(in), DIMENSION(npart_real) :: v_euler_y
double precision, intent(in), DIMENSION(npart_real) :: v_euler_z
double precision, intent(in), DIMENSION(npart_real) :: g_xx
double precision, intent(in), DIMENSION(npart_real) :: g_xy
double precision, intent(in), DIMENSION(npart_real) :: g_xz
double precision, intent(in), DIMENSION(npart_real) :: g_yy
double precision, intent(in), DIMENSION(npart_real) :: g_yz
double precision, intent(in), DIMENSION(npart_real) :: g_zz
double precision, intent(in), DIMENSION(npart_real) :: baryon_density
double precision, intent(out), DIMENSION(npart_real) :: nstar_p
subroutine get_nstar_p(npart_real, x, y, z, nstar_p)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
double precision, intent(in) :: x(npart_real)
double precision, intent(in) :: y(npart_real)
double precision, intent(in) :: z(npart_real)
double precision, intent(out) :: nstar_p(npart_real)
subroutine import_id(x, y, z, g_xx, baryon_density, gamma_euler)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
double precision, intent(inout) :: g_xx
double precision, intent(inout) :: baryon_density
double precision, intent(inout) :: gamma_euler
subroutine integrate_mass_density(center, radius, central_density, dr, dth, dphi, mass, mass_profile, mass_profile_idx)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: center
Center of the star
double precision, intent(in) :: radius
Radius of the star
double precision, intent(in) :: central_density
Central density of the star
double precision, intent(in) :: dr
Integration steps
double precision, intent(in) :: dth
Integration steps
double precision, intent(in) :: dphi
Integration steps
double precision, intent(inout) :: mass
Integrated mass of the star
double precision, intent(inout), DIMENSION(:,:), ALLOCATABLE :: mass_profile
Array storing the radial mass profile of the star
integer, intent(inout), DIMENSION(:), ALLOCATABLE :: mass_profile_idx
Array to store the indices for array mass_profile, sorted so that mass_profile[mass_profile_idx] is in increasing order
Call graph
construct_particles calls read_options, allocate_lorene_id_parts_memory, ktable, alive, impose_equatorial_plane_symmetry, timer, check_particle_positions, set_units, construct_particles
allocate_lorene_id_parts_memory calls allocate_lorene_id_parts_memory
impose_equatorial_plane_symmetry calls impose_equatorial_plane_symmetry, com
check_particle_positions calls indexx
particles calls construct_particles
sphincs_id calls particles
convergence_test calls particles