construct_ejecta – SPHINCS_ID
construct_ejecta Module Procedure
226 statements
Source File
module procedure construct_ejecta module module subroutine construct_ejecta(derived_type, filename) Interface →
Uses
constants
NR
pwp_EOS
Constructs an object of TYPE [[ejecta]]
Todo
to be OMP parallelized
FT xx.11.2021
Arguments
Type Intent Optional Attributes Name
class(ejecta), intent(out) :: derived_type
Constructed ejecta object
character(len=*), intent(in), optional :: filename
\(\texttt{LORENE}\) binary file containing the spectral DRS ID
Calls
Called by
Contents
Variables
atmosphere_density dphi dr dth epstmp exist finalnamefile grid_tmp header_lines i i_matter itr j k mass_profile mass_profile_idx n_matter_loc nlines ntmp rho_tmp rhotmp unit_pos vxtmp vytmp vztmp x_sorted xtmp y_sorted ytmp z_sorted ztmp
Variables
Type Visibility Attributes Name Initial
double precision, private, parameter :: atmosphere_density = 1.0439859633622731D-17
double precision, private :: dphi
double precision, private :: dr
double precision, private :: dth
double precision, private :: epstmp
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
double precision, private, DIMENSION(:,:), ALLOCATABLE :: grid_tmp
integer, private :: header_lines = 2
integer, private :: i
integer, private :: i_matter
integer, private :: itr
integer, private :: j
integer, private :: k
double precision, private, DIMENSION(:,:), ALLOCATABLE :: mass_profile
integer, private, DIMENSION(:), ALLOCATABLE :: mass_profile_idx
integer, private :: n_matter_loc
integer, private :: nlines
integer, private :: ntmp
double precision, private, DIMENSION(:,:,:), ALLOCATABLE :: rho_tmp
double precision, private :: rhotmp
integer, private, parameter :: unit_pos = 2589
double precision, private :: vxtmp
double precision, private :: vytmp
double precision, private :: vztmp
integer, private, DIMENSION(:), ALLOCATABLE :: x_sorted
double precision, private :: xtmp
integer, private, DIMENSION(:), ALLOCATABLE :: y_sorted
double precision, private :: ytmp
integer, private, DIMENSION(:), ALLOCATABLE :: z_sorted
double precision, private :: ztmp
Call graph
construct_ejecta calls get_p1, get_k1, get_gamma0, get_gamma3, get_rho_0, get_k2, get_k0, get_rho_1, get_rho_2, get_k3, get_gamma1, get_gamma2, select_eos_parameters, construct_ejecta
get_gamma0 calls get_gamma0
get_gamma3 calls get_gamma3
get_gamma1 calls get_gamma1
get_gamma2 calls get_gamma2