construct_binary – SPHINCS_LORENE
construct_binary Module Procedure
GNU Free Documentation License
25 statements
Source File
module procedure construct_binary module module subroutine construct_binary(THIS, resu_file) Interface →
Construct the \(\texttt{LORENE}\) \(\texttt{Bin_NS}\) object
FT
Arguments
Type Intent Optional Attributes Name
class(bnslorene), intent(inout) :: THIS
bnslorene object which this PROCEDURE is a member of
character(kind=C_CHAR,len=*), intent(in), optional :: resu_file
\(\texttt{LORENE}\) binary file containing the spectral BNS ID
Calls
Called by
Contents
Variables
default_case exist
Variables
Type Visibility Attributes Name Initial
character(kind=C_CHAR,len=7), private :: default_case
logical, private :: exist
Call graph
construct_binary calls destruct_bin_ns, construct_bin_ns, construct_binary