construct_diffstarlorene – SPHINCS_LORENE
construct_diffstarlorene Module Procedure
GNU Free Documentation License
16 statements
Source File
module procedure construct_diffstarlorene module module function construct_diffstarlorene(resu_file) result(drs) Interface →
Constructs an object of TYPE [[diffstarlorene]]
FT 25.10.2021
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: resu_file
\(\texttt{LORENE}\) binary file containing the spectral DRS ID
Return Value type(diffstarlorene)
Constructed diffstarlorene object
Calls
Called by
Contents
Variables
diffstar_counter
Variables
Type Visibility Attributes Name Initial
integer, private, SAVE :: diffstar_counter = 1
Call graph
construct_diffstarlorene calls import_diffstar_params, timer, construct_diffstarlorene
import_diffstar_params calls import_diffstar_params, get_diffstar_params, k_lorene2hydrobase_piecewisepolytrope, print_diffstar_params, k_lorene2hydrobase
print_diffstar_params calls print_diffstar_params, k_lorene2hydrobase
diffstarlorene calls construct_diffstarlorene
sphincs_lorene_bns calls diffstarlorene