construct_bssn – SPHINCS_ID
construct_bssn Module Procedure
36 statements
Source File
module procedure construct_bssn module module function construct_bssn(id, dx, dy, dz) result(bssnid) Interface →
Uses
Extract_Mass
McLachlan_refine
constants
mesh_refinement
This constructor of TYPE bssn calls the SUBROUTINES that rely on an idbase object, and allocates memory. It constructs the grid using the number of grid points along each axis.
FT 23.10.2020
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: id
idbase object to use to construct the bssn object
double precision, optional :: dx
Mesh spacings
Todo
for which refinement level?
double precision, optional :: dy
Mesh spacings
Todo
for which refinement level?
double precision, optional :: dz
Mesh spacings
Todo
for which refinement level?
Return Value type(bssn)
bssn object to be constructed
Calls
Called by
Contents
None
Call graph
construct_bssn calls deallocate_bssn, initialize_bssn, timer, construct_bssn
bssn calls construct_bssn
convergence_test calls bssn
sphincs_id calls bssn