construct_particles_std – SPHINCS_ID
construct_particles_std Module Procedure
905 statements
Source File
module procedure construct_particles_std module module function construct_particles_std(id, dist) result(parts) Interface →
Uses
analyze
kernel_table
bns_fuka
constants
units
utility
input_output
alive_flag
options
The constructor performs all the tasks needed to set up the particle distribution with the \(\mathrm{ID}\) evaluated on it. It calls all the PROCEDURES that rely on an object of STATIC TYPE idbase.
Todo
assign sub-tasks to separate SUBROUTINES contained in this SUBMODULE
FT 17.10.2020
Note
Last updated: FT 25.04.2022
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: id
idbase object representing the BNS for which we want to place particles
integer, intent(in) :: dist
Identifier of the desired particle distribution:
0: Read particle positions (and optionally the baryon number per particle) from a formatted file
1: Place particles on several lattices, each one surrounding a matter object
3: Place particles on spherical surfaces inside each matter object
Return Value type(particles)
Constructed particles object
Calls
Called by
Contents
Variables
a apm_iterate apm_max_it barycenter center central_density column_nu columns compose_eos compose_filename compose_path correct_nu counter debug exist file_exists filename_apm_pos filename_apm_pos_id filename_apm_results filename_mass_profile filename_shells_pos filename_shells_radii g00_lengthscales ghost_dist header_lines i_matter lapse_lengthscales last_r lower_bound lower_factor mass_it max_inc max_length max_mass max_steps min_eps min_g00_abs min_lapse min_vel n_cols n_matter_tmp nlines npart_des npart_des_i npart_i_tmp npart_tmp nu_ratio_des nuratio_des nuratio_thres nx_gh ny_gh nz_gh parts_all parts_pos parts_pos_namefile parts_pos_path phi_a print_step pvol_tmp r_a randomize_phi randomize_r randomize_theta read_nu redistribute_nu reflect_particles_x remove_atmosphere shift_norm sizes str_i stretch theta_a thres tmp tmp_pos tol_equal_mass total_mass unit_pos upper_bound upper_factor use_atmosphere use_thres xmax xmin ymax ymin zmax zmin
Derived Types
parts_i
Functions
import_density validate_position
Subroutines
compute_nstar_eul_id compute_nstar_id correct_center_of_mass_of_system get_nstar_id import_id integrate_mass_density reflect_particles_yz_plane
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, DIMENSION(id% get_n_matter()) :: apm_iterate
integer, private :: apm_max_it
double precision, private, DIMENSION(id% get_n_matter(),3) :: barycenter
double precision, private, DIMENSION(id% get_n_matter(),3) :: center
double precision, private, DIMENSION(id% get_n_matter()) :: central_density
integer, private :: column_nu
integer, private, DIMENSION(3) :: columns
logical, private :: compose_eos
character(len=max_length), private :: compose_filename
character(len=max_length), private :: compose_path
logical, private :: correct_nu
integer, private, SAVE :: counter = 1
logical, private, parameter :: debug = .FALSE.
logical, private :: exist
logical, private :: file_exists
character(len=max_length), private :: filename_apm_pos
character(len=max_length), private :: filename_apm_pos_id
character(len=max_length), private :: filename_apm_results
character(len=max_length), private :: filename_mass_profile
character(len=max_length), private :: filename_shells_pos
character(len=max_length), private :: filename_shells_radii
double precision, private, DIMENSION(id% get_n_matter()) :: g00_lengthscales
double precision, private :: ghost_dist
integer, private :: header_lines
integer, private :: i_matter
double precision, private, DIMENSION(id% get_n_matter()) :: lapse_lengthscales
double precision, private :: last_r
double precision, private :: lower_bound
double precision, private :: lower_factor
logical, private :: mass_it
integer, private :: max_inc
integer, private, parameter :: max_length = 50
double precision, private :: max_mass
integer, private :: max_steps
double precision, private :: min_eps
double precision, private :: min_g00_abs
double precision, private :: min_lapse
double precision, private :: min_vel
integer, private :: n_cols
integer, private :: n_matter_tmp
integer, private :: nlines
integer, private :: npart_des
integer, private, DIMENSION(id% get_n_matter()) :: npart_des_i
integer, private, DIMENSION(:), ALLOCATABLE :: npart_i_tmp
integer, private :: npart_tmp
double precision, private :: nu_ratio_des
double precision, private :: nuratio_des
double precision, private :: nuratio_thres
integer, private :: nx_gh
integer, private :: ny_gh
integer, private :: nz_gh
type(parts_i), private, DIMENSION(id% get_n_matter()) :: parts_all
character(len=max_length), private :: parts_pos
character(len=:), private, ALLOCATABLE :: parts_pos_namefile
character(len=max_length), private :: parts_pos_path
double precision, private :: phi_a
integer, private :: print_step
double precision, private :: pvol_tmp
double precision, private :: r_a
logical, private :: randomize_phi
logical, private :: randomize_r
logical, private :: randomize_theta
logical, private :: read_nu
logical, private :: redistribute_nu
logical, private :: reflect_particles_x
logical, private, DIMENSION(id% get_n_matter()) :: remove_atmosphere
double precision, private :: shift_norm
double precision, private, DIMENSION(id% get_n_matter(),6) :: sizes
character(len=3), private :: str_i
double precision, private :: stretch
double precision, private :: theta_a
double precision, private :: thres
integer, private :: tmp
double precision, private, DIMENSION(:, :), ALLOCATABLE :: tmp_pos
double precision, private, parameter :: tol_equal_mass = 5.0D-3
double precision, private :: total_mass
integer, private, parameter :: unit_pos = 2289
double precision, private :: upper_bound
double precision, private :: upper_factor
logical, private, DIMENSION(id% get_n_matter()) :: use_atmosphere
logical, private :: use_thres
double precision, private :: xmax
double precision, private :: xmin
double precision, private :: ymax
double precision, private :: ymin
double precision, private :: zmax
double precision, private :: zmin
Derived Types
type :: parts_i
Components
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:), ALLOCATABLE :: h_i
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_i
double precision, private, DIMENSION(:), ALLOCATABLE :: pmass_i
double precision, private, DIMENSION(:, :), ALLOCATABLE :: pos_i
double precision, private, DIMENSION(:), ALLOCATABLE :: pvol_i
Functions
function import_density(x, y, z) result(density)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value double precision
function validate_position(x, y, z) result(answer)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value logical
Subroutines
subroutine compute_nstar_eul_id(npart, v_euler_x, v_euler_y, v_euler_z, g_xx, g_xy, g_xz, g_yy, g_yz, g_zz, baryon_density, nstar_eul_id)
Compute nstar_eul_id, the relativistic baryon mass density seen by the Eulerian observer, given the \(\mathrm{ID}\)
FT 31.08.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(in), DIMENSION(npart) :: v_euler_x
double precision, intent(in), DIMENSION(npart) :: v_euler_y
double precision, intent(in), DIMENSION(npart) :: v_euler_z
double precision, intent(in), DIMENSION(npart) :: g_xx
double precision, intent(in), DIMENSION(npart) :: g_xy
double precision, intent(in), DIMENSION(npart) :: g_xz
double precision, intent(in), DIMENSION(npart) :: g_yy
double precision, intent(in), DIMENSION(npart) :: g_yz
double precision, intent(in), DIMENSION(npart) :: g_zz
double precision, intent(in), DIMENSION(npart) :: baryon_density
double precision, intent(out), DIMENSION(npart) :: nstar_eul_id
subroutine compute_nstar_id(npart, lapse, shift_x, shift_y, shift_z, v_euler_x, v_euler_y, v_euler_z, g_xx, g_xy, g_xz, g_yy, g_yz, g_zz, baryon_density, nstar_sph, nstar_id, nlrf_sph, sqg)
Compute nstar_id, the proper baryon mass density, given the \(\mathrm{ID}\)
FT 31.08.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(in), DIMENSION(npart) :: lapse
double precision, intent(in), DIMENSION(npart) :: shift_x
double precision, intent(in), DIMENSION(npart) :: shift_y
double precision, intent(in), DIMENSION(npart) :: shift_z
double precision, intent(in), DIMENSION(npart) :: v_euler_x
double precision, intent(in), DIMENSION(npart) :: v_euler_y
double precision, intent(in), DIMENSION(npart) :: v_euler_z
double precision, intent(in), DIMENSION(npart) :: g_xx
double precision, intent(in), DIMENSION(npart) :: g_xy
double precision, intent(in), DIMENSION(npart) :: g_xz
double precision, intent(in), DIMENSION(npart) :: g_yy
double precision, intent(in), DIMENSION(npart) :: g_yz
double precision, intent(in), DIMENSION(npart) :: g_zz
double precision, intent(in), DIMENSION(npart) :: baryon_density
double precision, intent(in), DIMENSION(npart) :: nstar_sph
double precision, intent(out), DIMENSION(npart) :: nstar_id
double precision, intent(out), DIMENSION(npart) :: nlrf_sph
double precision, intent(out), DIMENSION(npart) :: sqg
subroutine correct_center_of_mass_of_system(npart, pos, nu, com_system)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(inout) :: pos(3,npart)
double precision, intent(inout) :: nu(npart)
double precision, intent(in) :: com_system(3)
subroutine get_nstar_id(npart, x, y, z, nstar_sph, nstar_id, nlrf_sph, sqg)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(in) :: x(npart)
double precision, intent(in) :: y(npart)
double precision, intent(in) :: z(npart)
double precision, intent(in) :: nstar_sph(npart)
double precision, intent(out) :: nstar_id(npart)
double precision, intent(out) :: nlrf_sph(npart)
double precision, intent(out) :: sqg(npart)
subroutine import_id(x, y, z, sqdetg, baryon_density, gamma_euler)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
double precision, intent(out) :: sqdetg
double precision, intent(out) :: baryon_density
double precision, intent(out) :: gamma_euler
subroutine integrate_mass_density(center, radius, central_density, dr, dth, dphi, mass, mass_profile, mass_profile_idx)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: center
Center of the star
double precision, intent(in) :: radius
Radius of the star
double precision, intent(in) :: central_density
Central density of the star
double precision, intent(in) :: dr
Integration steps
double precision, intent(in) :: dth
Integration steps
double precision, intent(in) :: dphi
Integration steps
double precision, intent(inout) :: mass
Integrated mass of the star
double precision, intent(out), DIMENSION(3,0:NINT(radius/dr)) :: mass_profile
Array storing the radial mass profile of the star
integer, intent(out), DIMENSION(0:NINT(radius/dr)) :: mass_profile_idx
Array to store the indices for array mass_profile, sorted so that mass_profile[mass_profile_idx] is in increasing order INTEGER, DIMENSION(:), ALLOCATABLE, INTENT(INOUT):: mass_profile_idx
subroutine reflect_particles_yz_plane(pos_star1, pvol_star1, pmass_star1, nu_star1, h_star1, npart_star1, pos_star2, pvol_star2, pmass_star2, nu_star2, h_star2, npart_star2)
Reflect particles of star 1 with respect to the plane and place them on star 2
FT 07.02.2022
Arguments
Type Intent Optional Attributes Name
double precision, intent(in), DIMENSION(:,:) :: pos_star1
Array where to store the particle positions for star 1
double precision, intent(in), DIMENSION(:) :: pvol_star1
Array where to store the particle volumes for star 1
double precision, intent(in), DIMENSION(:) :: pmass_star1
Array where to store the particle masses for star 1
double precision, intent(in), DIMENSION(:) :: nu_star1
Array where to store the particle baryon number for star 1
double precision, intent(in), DIMENSION(:) :: h_star1
Array where to store the particle smoothing lengths for star 1
integer, intent(in) :: npart_star1
Variable where to store the particle number for star 1
double precision, intent(inout), DIMENSION(:,:), ALLOCATABLE :: pos_star2
Array where to store the particle positions for star 2
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: pvol_star2
Array where to store the particle volumes for star 2
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: pmass_star2
Array where to store the particle masses for star 2
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: nu_star2
Array where to store the particle baryon number for star 2
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: h_star2
Array where to store the particle smoothing lengths for star 2
integer, intent(inout) :: npart_star2
Variable where to store the particle number for star 2
Call graph
construct_particles_std calls check_particle_positions, spherical_from_cartesian, timer, allocate_particles_memory, correct_center_of_mass, reflect_particles_yz_plane, com, spatial_vector_norm_sym3x3, read_options, alive, ktable, impose_equatorial_plane_symmetry, set_units, construct_particles_std
check_particle_positions calls check_particle_positions, indexx
allocate_particles_memory calls allocate_particles_memory
correct_center_of_mass calls correct_center_of_mass, com, is_finite_number
impose_equatorial_plane_symmetry calls impose_equatorial_plane_symmetry, com, find_particles_above_xy_plane, reflect_particles_xy_plane
find_particles_above_xy_plane calls find_particles_above_xy_plane
reflect_particles_xy_plane calls reflect_particles_xy_plane
particles calls construct_particles_std
convergence_test calls particles
sphincs_id calls particles