construct_bnsfuka – SPHINCS_ID
construct_bnsfuka Module Procedure
32 statements
Source File
module procedure construct_bnsfuka module module subroutine construct_bnsfuka(derived_type, filename) Interface →
Uses
utility
Constructs an object of TYPE [[bnsfuka]]
Created: FT 09.02.2022 Last update: FT 27.05.2022
Arguments
Type Intent Optional Attributes Name
class(bnsfuka), intent(out) :: derived_type
Constructed bnsfuka object
character(len=*), intent(in), optional :: filename
\(\texttt{FUKA}\) binary file containing the spectral \(\mathrm{BNS}\) \(\mathrm{ID}\)
Calls
Called by
Contents
Variables
bns_counter length_scale_pressure
Functions
get_pressure
Variables
Type Visibility Attributes Name Initial
integer, private, SAVE :: bns_counter = 1
double precision, private, DIMENSION(:), ALLOCATABLE :: length_scale_pressure
Functions
function get_pressure(x, y, z) result(val)
Returns the value of the pressure at the desired point
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value double precision
Pressure at
Call graph
construct_bnsfuka calls timer, read_fuka_id_params, construct_bnsfuka
read_fuka_id_params calls read_fuka_id_params, get_fuka_id_params