construct_bssn_id – SPHINCS_LORENE
construct_bssn_id Module Procedure
GNU Free Documentation License
20 statements
Source File
module procedure construct_bssn_id module module function construct_bssn_id(id, dx, dy, dz) result(bssnid) Interface →
Uses
mesh_refinement
McLachlan_refine
Extract_Mass
This constructor of TYPE bssn_id calls the * SUBROUTINES that rely on an bns object, and * allocates memory. It constructs the grid * using the number of grid points along each axis. * * FT 23.10.2020 * *
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: id
double precision, optional :: dx
double precision, optional :: dy
double precision, optional :: dz
Return Value type(bssn_id)
Calls
Called by
Contents
None
Call graph
construct_bssn_id calls initialize_bssn, allocate_bssn_fields, timer, deallocate_bssn, construct_bssn_id
allocate_bssn_fields calls allocate_bssn_fields, allocate_grid_function
bssn_id calls construct_bssn_id
convergence_test calls bssn_id
sphincs_lorene_bns calls bssn_id