construct_bnslorene – SPHINCS_ID
construct_bnslorene Module Procedure
35 statements
Source File
module procedure construct_bnslorene module module subroutine construct_bnslorene(derived_type, filename) Interface →
Uses
utility
Constructs an object of TYPE [[bnslorene]]
FT
Arguments
Type Intent Optional Attributes Name
class(bnslorene), intent(out) :: derived_type
Constructed bnslorene object
character(len=*), intent(in), optional :: filename
\(\texttt{LORENE}\) binary file containing the spectral BNS ID
Calls
Called by
Contents
Variables
bns_counter length_scale_pressure
Functions
get_pressure
Variables
Type Visibility Attributes Name Initial
integer, private, SAVE :: bns_counter = 1
double precision, private, DIMENSION(:), ALLOCATABLE :: length_scale_pressure
Functions
function get_pressure(x, y, z) result(val)
Returns the value of the pressure at the desired point
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value double precision
Pressure at
Call graph
construct_bnslorene calls timer, import_id_params, construct_bnslorene
import_id_params calls import_id_params, k_lorene2hydrobase_piecewisepolytrope, shorten_eos_name, print_id_params, get_lorene_id_params, k_lorene2hydrobase
print_id_params calls print_id_params, k_lorene2hydrobase