construct_particles_bin – SPHINCS_ID
construct_particles_bin Module Procedure
102 statements
Source File
module procedure construct_particles_bin module module function construct_particles_bin(id, namefile) result(parts) Interface →
Uses
tensor
input_output
pwp_EOS
units
sph_variables
constants
utility
options
omp_lib
Constructs a [[particles]] object from an \(\mathrm{ID}\) binary file
FT 01.03.2022
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: id
idbase object representing the BNS for which we want to place particles
character(len=*), intent(inout) :: namefile
Name of the \(\mathrm{ID}\) binary file
Return Value type(particles)
Constructed particles object
Calls
Called by
Contents
Variables
a det g4 sq_detg4 tmp tmp1 tmp10 tmp2 tmp3 tmp4 tmp5 tmp6 tmp7 tmp8 tmp9 v_norm
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private :: det
double precision, private :: g4(n_sym4x4)
double precision, private, DIMENSION(:), ALLOCATABLE :: sq_detg4
integer, private :: tmp
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp1
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp10
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp2
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp3
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp4
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp5
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp6
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp7
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp8
double precision, private, DIMENSION(:), ALLOCATABLE :: tmp9
double precision, private :: v_norm
Call graph
construct_particles_bin calls spacetime_vector_norm_sym4x4, deallocate_sph_memory, allocate_sph_memory, read_options, determinant_sym4x4, set_units, omp_set_num_threads, select_eos_parameters, compute_g4, construct_particles_bin
particles calls construct_particles_bin
sphincs_id calls particles
convergence_test calls particles