correct_center_of_mass – SPHINCS_ID
correct_center_of_mass Subroutine
62 statements
Source File
subroutine correct_center_of_mass(npart_real, pos, nu, get_density, validate_pos, com_star, verbose)
Uses
analyze
Translate the particles so that their center of mass coincides with the center of mass of the star, given by LORENE
FT 1.09.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
double precision, intent(inout), DIMENSION(3,npart_real) :: pos
double precision, intent(inout), DIMENSION(npart_real) :: nu
function get_density(x, y, z) result(density)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value double precision
function validate_pos(x, y, z) result(answer)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
double precision, intent(in) :: y
double precision, intent(in) :: z
Return Value logical
double precision, intent(in), DIMENSION(3) :: com_star
logical, intent(in), optional :: verbose
Calls
Called by
Contents
Variables
a com_d com_x com_y com_z pos_corr_tmp
Source Code
correct_center_of_mass
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private :: com_d
double precision, private :: com_x
double precision, private :: com_y
double precision, private :: com_z
double precision, private, DIMENSION(3) :: pos_corr_tmp
Source Code
  SUBROUTINE correct_center_of_mass( npart_real, pos, nu, get_density, &
                                     validate_pos, com_star, verbose )
    !***********************************************************
    !
    !# Translate the particles so that their center of mass
    !  coincides with the center of mass of the star, given by
    !  LORENE
    !
    !  FT 1.09.2021
    !
    !***********************************************************
    USE analyze, ONLY: COM
    IMPLICIT NONE
    INTEGER, INTENT(IN):: npart_real
    DOUBLE PRECISION, DIMENSION(3), INTENT(IN):: com_star
    LOGICAL, INTENT(IN), OPTIONAL:: verbose
    INTERFACE
      FUNCTION get_density( x, y, z ) RESULT( density )
        DOUBLE PRECISION, INTENT(IN):: x
        DOUBLE PRECISION, INTENT(IN):: y
        DOUBLE PRECISION, INTENT(IN):: z
        DOUBLE PRECISION:: density
      END FUNCTION
    END INTERFACE
    INTERFACE
      FUNCTION validate_pos( x, y, z ) RESULT( answer )
        DOUBLE PRECISION, INTENT(IN):: x
        DOUBLE PRECISION, INTENT(IN):: y
        DOUBLE PRECISION, INTENT(IN):: z
        LOGICAL:: answer
      END FUNCTION
    END INTERFACE
    DOUBLE PRECISION, DIMENSION(3,npart_real), INTENT(INOUT):: pos
    DOUBLE PRECISION, DIMENSION(npart_real),   INTENT(INOUT):: nu
    INTEGER:: a
    DOUBLE PRECISION:: com_x, com_y, com_z, com_d
    DOUBLE PRECISION, DIMENSION(3):: pos_corr_tmp
    CALL COM( npart_real, pos, nu, &       ! input
              com_x, com_y, com_z, com_d ) ! output
    IF( PRESENT(verbose) .AND. verbose .EQV. .TRUE. )THEN
      PRINT *, "** Before center of mass correction:"
      PRINT *, " * x coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(1), "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(2), "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(3), "Msun_geo"
      PRINT *, " * x coordinate of the center of mass of the particle ", &
               "distribution: com_x= ", com_x, "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the particle ", &
               "distribution: com_y= ", com_y, "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the particle ", &
               "distribution: com_z= ", com_z, "Msun_geo"
      PRINT *, " * Distance of the center of mass of the particle ", &
               "distribution from the  origin: com_d= ", com_d
      PRINT *, " * |com_x-com_star_x/com_star_x|=", &
               ABS( com_x-com_star(1) )/ABS( com_star(1) + 1 )
      PRINT *
    ENDIF
    !$OMP PARALLEL DO DEFAULT( NONE ) &
    !$OMP             SHARED( pos, com_star, &
    !$OMP                     com_x, com_y, com_z, npart_real ) &
    !$OMP             PRIVATE( pos_corr_tmp, a )
    DO a= 1, npart_real, 1
      pos_corr_tmp(1)= pos(1,a) - ( com_x - com_star(1) )
      pos_corr_tmp(2)= pos(2,a) - ( com_y - com_star(2) )
      pos_corr_tmp(3)= pos(3,a) - ( com_z - com_star(3) )
      IF( get_density( &
                  pos_corr_tmp(1), pos_corr_tmp(2), pos_corr_tmp(3) ) > zero &
          .AND. &
          validate_pos( &
                  pos_corr_tmp(1), pos_corr_tmp(2), pos_corr_tmp(3) ) == 0 &
      )THEN
        pos(:,a)= pos_corr_tmp
      ENDIF
    ENDDO
    !$OMP END PARALLEL DO
    CALL COM( npart_real, pos, nu, & ! input
              com_x, com_y, com_z, com_d ) ! output
    IF( PRESENT(verbose) .AND. verbose .EQV. .TRUE. )THEN
      PRINT *, "** After center of mass correction:"
      PRINT *, " * x coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(1), "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(2), "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the star, ", &
               "from the ID: com_star= ", com_star(3), "Msun_geo"
      PRINT *, " * x coordinate of the center of mass of the particle ", &
               "distribution: com_x= ", com_x, "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the particle ", &
               "distribution: com_y= ", com_y, "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the particle ", &
               "distribution: com_z= ", com_z, "Msun_geo"
      PRINT *, " * Distance of the center of mass of the particle ", &
               "distribution from the  origin: com_d= ", com_d
      PRINT *, " * |com_x-com_star_x/com_star_x|=", &
               ABS( com_x-com_star(1) )/ABS( com_star(1) + 1 )
      PRINT *
    ENDIF
  END SUBROUTINE correct_center_of_mass
Call graph
correct_center_of_mass calls com
perform_apm calls correct_center_of_mass, perform_apm