deallocate_bssn_fields – SPHINCS_LORENE
deallocate_bssn_fields Module Procedure
GNU Free Documentation License
22 statements
Source File
module procedure deallocate_bssn_fields module module subroutine deallocate_bssn_fields(THIS) Interface →
Uses
mesh_refinement
Arguments
Type Intent Optional Attributes Name
class(bssn_id), intent(inout) :: THIS
Calls
Called by
Contents
None
Call graph
deallocate_bssn_fields calls deallocate_grid_function, deallocate_bssn_fields
destruct_bssn_id calls deallocate_bssn_fields, destruct_bssn_id
destructor calls destruct_bssn_id, destructor