destruct_bssn_id – SPHINCS_ID
destruct_bssn_id Module Procedure
GNU Free Documentation License
4 statements
Source File
module procedure destruct_bssn_id module module subroutine destruct_bssn_id(THIS) Interface →
Arguments
Type Intent Optional Attributes Name
class(bssn_id), intent(inout) :: THIS
Calls
Called by
Contents
None
Call graph
destruct_bssn_id calls deallocate_bssn_fields, destruct_bssn_id
deallocate_bssn_fields calls deallocate_bssn_fields, deallocate_grid_function
destructor calls destruct_bssn_id, destructor