destructor – SPHINCS_ID
destructor Module Procedure
7 statements
Source File
module procedure destructor module module subroutine destructor(this) Interface →
Destructor of EXTENDED TYPE bssn
FT
Arguments
Type Intent Optional Attributes Name
type(bssn), intent(inout) :: this
bssn object to which this PROCEDURE is bound, to be destructed
Calls
Called by
Contents
None
Call graph
destructor calls deallocate_standard_tpo_variables, destruct_bssn, destructor
destruct_bssn calls destruct_bssn, deallocate_bssn_fields
deallocate_bssn_fields calls deallocate_bssn_fields, deallocate_grid_function