determinant_sym3x3 – SPHINCS_ID
determinant_sym3x3 Subroutine
11 statements
Source File
public subroutine determinant_sym3x3(A, det)
Uses
tensor
Compute the determinant of a symmetric matrix field, given as a 6-vector, at a given grid point
FT 26.03.2021
Generalized to not be bound to the mesh
FT 07.02.2022
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: A(jxx:jzz)
The symmetric matrix, given as a 6-vector.
double precision, intent(out) :: det
Determinant of the symmetric matrix
Called by
Contents
Source Code
determinant_sym3x3
Source Code
  SUBROUTINE determinant_sym3x3( A, det )
    !****************************************************************
    !
    !# Compute the determinant of a \(3\times 3\) symmetric matrix
    !  field, given as a 6-vector, at a given grid point
    !
    !  FT 26.03.2021
    !
    !  Generalized to not be bound to the mesh
    !
    !  FT 07.02.2022
    !
    !****************************************************************
    USE tensor, ONLY: jxx, jxy, jxz, jyy, jyz, jzz, n_sym3x3
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN):: A(jxx:jzz)
    !# The \(3\times 3\) symmetric matrix, given as a 6-vector.
    DOUBLE PRECISION, INTENT(OUT):: det
    !! Determinant of the \(3\times 3\) symmetric matrix
    IF( SIZE(A) /= n_sym3x3 )THEN
      PRINT *, "** ERROR in determinant_sym3x3_grid in MODULE utility.", &
               " This subroutine needs an array with 6 components,",&
               " and a ", SIZE(A), "component array was given instead."
      STOP
    ENDIF
    det=   A(jxx)*A(jyy)*A(jzz) &
         + A(jxy)*A(jyz)*A(jxz) &
         + A(jxz)*A(jxy)*A(jyz) &
         - A(jxy)*A(jxy)*A(jzz) &
         - A(jxz)*A(jyy)*A(jxz) &
         - A(jxx)*A(jyz)*A(jyz)
  END SUBROUTINE determinant_sym3x3
Call graph
import_id_particles calls determinant_sym3x3, import_id_particles
read_fuka_id_spacetime calls determinant_sym3x3, read_fuka_id_spacetime
read_fuka_id_particles calls determinant_sym3x3, read_fuka_id_particles
setup_standard_tpo_variables calls determinant_sym3x3, setup_standard_tpo_variables
integrate_baryon_mass_density calls determinant_sym3x3, integrate_baryon_mass_density
analyze_constraint calls determinant_sym3x3, analyze_constraint