find_particles_above_xy_plane – SPHINCS_ID
find_particles_above_xy_plane Module Procedure
55 statements
Source File
module procedure find_particles_above_xy_plane module module subroutine find_particles_above_xy_plane(npart, pos, npart_above_xy, above_xy_plane_a) Interface →
Uses
utility
Find the particles above the plane
FT 25.03.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(in), DIMENSION(3,npart) :: pos
integer, intent(out) :: npart_above_xy
integer, intent(out), DIMENSION(:), ALLOCATABLE :: above_xy_plane_a
Called by
Contents
Variables
a above_xy_plane above_xy_plane_a_tmp below_xy_plane below_xy_plane_a_tmp npart_diff
Variables
Type Visibility Attributes Name Initial
integer, private :: a
integer, private, DIMENSION(npart) :: above_xy_plane
double precision, private, DIMENSION(:), ALLOCATABLE :: above_xy_plane_a_tmp
integer, private, DIMENSION(npart) :: below_xy_plane
double precision, private, DIMENSION(:), ALLOCATABLE :: below_xy_plane_a_tmp
integer, private :: npart_diff
Call graph
find_particles_above_xy_plane calls find_particles_above_xy_plane
impose_equatorial_plane_symmetry calls find_particles_above_xy_plane, impose_equatorial_plane_symmetry
perform_apm calls impose_equatorial_plane_symmetry, perform_apm
construct_particles_std calls impose_equatorial_plane_symmetry, construct_particles_std
particles calls construct_particles_std
convergence_test calls particles
sphincs_id calls particles