import_diffstar_params – SPHINCS_ID
import_diffstar_params Module Procedure
59 statements
Source File
module procedure import_diffstar_params module module subroutine import_diffstar_params(this) Interface →
Uses
utility
sphincs_id_full
iso_c_binding
sphincs_id_lorene
Store the parameters of the binary neutron stars' \(\texttt{LORENE}\) ID into member variables
FT 5.10.2020
Arguments
Type Intent Optional Attributes Name
class(diffstarlorene), intent(inout) :: this
diffstarlorene object which this PROCEDURE is a member of
Calls
Called by
Contents
Variables
eos_tmp_c i nchars str_length
Variables
Type Visibility Attributes Name Initial
character(kind=C_CHAR), private, DIMENSION(str_length) :: eos_tmp_c
integer, private :: i
integer, private :: nchars
integer, private, parameter :: str_length = 100
Call graph
import_diffstar_params calls k_lorene2hydrobase_piecewisepolytrope, shorten_eos_name, print_diffstar_params, get_diffstar_params, k_lorene2hydrobase, import_diffstar_params
print_diffstar_params calls print_diffstar_params, k_lorene2hydrobase
construct_diffstarlorene calls import_diffstar_params, construct_diffstarlorene