import_id_spacetime – SPHINCS_ID
import_id_spacetime Module Procedure
GNU Free Documentation License
81 statements
Source File
module procedure import_id_spacetime module module subroutine import_id_spacetime(THIS, nx, ny, nz, pos, lapse, shift, g, ek) Interface →
Uses
constants
tensor
Stores the spacetime ID in multi-dimensional arrays needed to compute the BSSN variables and constraints
FT 22.11.2020
Arguments
Type Intent Optional Attributes Name
class(diffstarlorene), intent(inout) :: THIS
diffstarlorene object which this PROCEDURE is a member of
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: nz
double precision, intent(in), DIMENSION(:,:,:,:) :: pos
double precision, intent(inout), DIMENSION(:,:,:) :: lapse
double precision, intent(inout), DIMENSION(:,:,:,:) :: shift
double precision, intent(inout), DIMENSION(:,:,:,:) :: g
double precision, intent(inout), DIMENSION(:,:,:,:) :: ek
Calls
Called by
Contents
Variables
detg detg4 g4 i j k
Variables
Type Visibility Attributes Name Initial
double precision, private :: detg
double precision, private :: detg4
double precision, private, DIMENSION(:, :, :, :), ALLOCATABLE :: g4
integer, private :: i
integer, private :: j
integer, private :: k
Call graph
import_id_spacetime calls compute_g4, get_diffstar_spacetime, determinant_sym4x4_grid, import_id_spacetime