impose_equatorial_plane_symmetry – SPHINCS_LORENE
impose_equatorial_plane_symmetry Subroutine
GNU Free Documentation License
43 statements
Source File
subroutine impose_equatorial_plane_symmetry(npart_real, pos, nu, com_star, verbose)
Uses
analyze
Mirror the particle with z>0 with respect to the xy plane, to impose the equatorial-plane symmetry
FT 1.09.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
double precision, intent(inout), DIMENSION(3,npart_real) :: pos
double precision, intent(inout), DIMENSION(npart_real) :: nu
double precision, intent(in), optional :: com_star
logical, intent(in), optional :: verbose
Calls
Called by
Contents
Variables
a com_d com_x com_y com_z itr npart_real_half nu_tmp pos_tmp
Source Code
impose_equatorial_plane_symmetry
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private :: com_d
double precision, private :: com_x
double precision, private :: com_y
double precision, private :: com_z
integer, private :: itr
integer, private :: npart_real_half
double precision, private, DIMENSION(npart_real) :: nu_tmp
double precision, private, DIMENSION(3,npart_real) :: pos_tmp
Source Code
  SUBROUTINE impose_equatorial_plane_symmetry( npart_real, pos, nu, com_star, &
                                               verbose )
    !*************************************************************
    !
    !# Mirror the particle with z>0 with respect to the xy plane,
    !  to impose the equatorial-plane symmetry
    !
    !  FT 1.09.2021
    !
    !*************************************************************
    USE analyze, ONLY: COM
    IMPLICIT NONE
    INTEGER, INTENT(IN):: npart_real
    DOUBLE PRECISION, INTENT(IN), OPTIONAL:: com_star
    LOGICAL, INTENT(IN), OPTIONAL:: verbose
    DOUBLE PRECISION, DIMENSION(3,npart_real), INTENT(INOUT):: pos
    DOUBLE PRECISION, DIMENSION(npart_real),   INTENT(INOUT):: nu
    INTEGER:: a, itr, npart_real_half
    DOUBLE PRECISION:: com_x, com_y, com_z, com_d
    DOUBLE PRECISION, DIMENSION(3,npart_real):: pos_tmp
    DOUBLE PRECISION, DIMENSION(npart_real)  :: nu_tmp
    pos_tmp= pos
    nu_tmp= nu
    itr= 0
    DO a= 1, npart_real, 1
      IF( pos_tmp( 3, a ) > 0.0D0 &
          .AND. &
          itr < npart_real/2 )THEN
        itr= itr + 1
        pos( 1, itr )= pos_tmp( 1, a )
        pos( 2, itr )= pos_tmp( 2, a )
        pos( 3, itr )= pos_tmp( 3, a )
        nu( itr )    = nu_tmp( a )
      ENDIF
    ENDDO
    npart_real_half= itr
    ! If some of the particles crossed the xy plane top-down in the
    ! last step, replace them with their previous position
    ! above the xy plane
!   IF(npart_real_half < npart_real/2)THEN
!
!     npart_missing= npart_real/2 - npart_real_half
!
!     DO a= npart_real_half + 1, npart_real/2, 1
!
!       pos(:, a)= all_pos_tmp2(:, a)
!
!     ENDDO
!
!   ENDIF
    !$OMP PARALLEL DO DEFAULT( NONE ) &
    !$OMP             SHARED( pos, npart_real_half, nu ) &
    !$OMP             PRIVATE( a )
    DO a= 1, npart_real_half, 1
      pos( 1, npart_real_half + a )=   pos( 1, a )
      pos( 2, npart_real_half + a )=   pos( 2, a )
      pos( 3, npart_real_half + a )= - pos( 3, a )
      nu( npart_real_half + a )    =   nu( a )
    ENDDO
    !$OMP END PARALLEL DO
    IF( PRESENT(verbose) .AND. verbose .EQV. .TRUE. )THEN
      CALL COM( npart_real, pos, nu, & ! input
                com_x, com_y, com_z, com_d ) ! output
      PRINT *, "** After mirroring particles:"
      IF( PRESENT(com_star) ) PRINT *, &
               " * x coordinate of the center of mass of the star, ", &
               "from LORENE: com_star= ", com_star, "Msun_geo"
      PRINT *, " * x coordinate of the center of mass of the particle ", &
               "distribution: com_x= ", com_x, "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the particle ", &
               "distribution: com_y= ", com_y, "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the particle ", &
               "distribution: com_z= ", com_z, "Msun_geo"
      PRINT *, " * Distance of the center of mass of the particle ", &
               "distribution from the  origin: com_d= ", com_d
      IF( PRESENT(com_star) ) PRINT *, " * |com_x-com_star/com_star|=", &
               ABS( com_x-com_star )/ABS( com_star + 1 )
      PRINT *
    ENDIF
  END SUBROUTINE impose_equatorial_plane_symmetry
Call graph
impose_equatorial_plane_symmetry calls com
perform_apm calls impose_equatorial_plane_symmetry, perform_apm