impose_equatorial_plane_symmetry_apm – SPHINCS_ID
impose_equatorial_plane_symmetry_apm Subroutine
103 statements
Source File
subroutine impose_equatorial_plane_symmetry_apm(npart_all, npart_real, npart_ghost, pos, fld, nu, com_star, verbose)
Uses
analyze
sph_variables
constants
Mirror the particle with z>0 with respect to the xy plane, to impose the equatorial-plane symmetry
FT 1.09.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: npart_all
integer, intent(inout) :: npart_real
integer, intent(in) :: npart_ghost
double precision, intent(inout), DIMENSION(:,:), ALLOCATABLE :: pos
type(apm_fields), intent(inout) :: fld
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: nu
double precision, intent(in), optional :: com_star
logical, intent(in), optional :: verbose
Calls
Called by
Contents
Variables
a above_xy_plane_a all_pos_prev_dump_tmp com_d com_x com_y com_z exist finalnamefile h_fac htmp npart_above_xy npart_real_old nstar_id_tmp nu_below nutmp pos_below postmp
Source Code
impose_equatorial_plane_symmetry_apm
Variables
Type Visibility Attributes Name Initial
integer, private :: a
integer, private, DIMENSION(:), ALLOCATABLE :: above_xy_plane_a
double precision, private, DIMENSION(3,npart_all) :: all_pos_prev_dump_tmp
double precision, private :: com_d
double precision, private :: com_x
double precision, private :: com_y
double precision, private :: com_z
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
double precision, private, parameter :: h_fac = 1.1D0
Factor that multiplies the smoothing lengths, after the particles (with their properties) have been reflected
double precision, private, DIMENSION(npart_all) :: htmp
integer, private :: npart_above_xy
integer, private :: npart_real_old
double precision, private, DIMENSION(npart_all) :: nstar_id_tmp
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_below
double precision, private, DIMENSION(npart_all) :: nutmp
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos_below
double precision, private, DIMENSION(3,npart_all) :: postmp
Source Code
  SUBROUTINE impose_equatorial_plane_symmetry_apm( npart_all, npart_real, &
                                                   npart_ghost, pos, fld, nu, &
                                                   com_star, verbose )
    !*************************************************************
    !
    !# Mirror the particle with z>0 with respect to the xy plane,
    !  to impose the equatorial-plane symmetry
    !
    !  FT 1.09.2021
    !
    !*************************************************************
    USE constants,      ONLY: zero
    USE analyze,        ONLY: COM
    USE sph_variables,  ONLY: h
    IMPLICIT NONE
    DOUBLE PRECISION, PARAMETER:: h_fac= 1.1D0
    !# Factor that multiplies the smoothing lengths, after the particles
    !  (with their properties) have been reflected
    INTEGER, INTENT(INOUT):: npart_all
    INTEGER, INTENT(INOUT):: npart_real
    INTEGER, INTENT(IN)   :: npart_ghost
    INTEGER:: npart_real_old
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE, INTENT(INOUT):: pos
    TYPE(apm_fields), INTENT(INOUT):: fld
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE,   INTENT(INOUT):: nu
    DOUBLE PRECISION,                     INTENT(IN),    OPTIONAL:: com_star
    LOGICAL,                              INTENT(IN),    OPTIONAL:: verbose
    INTEGER:: a, npart_above_xy
    DOUBLE PRECISION:: com_x, com_y, com_z, com_d
    INTEGER, DIMENSION(:), ALLOCATABLE:: above_xy_plane_a
    DOUBLE PRECISION, DIMENSION(3,npart_all):: postmp
    DOUBLE PRECISION, DIMENSION(npart_all)  :: nutmp
    DOUBLE PRECISION, DIMENSION(npart_all)  :: htmp
    DOUBLE PRECISION, DIMENSION(npart_all)  :: nstar_id_tmp
    DOUBLE PRECISION, DIMENSION(3,npart_all):: all_pos_prev_dump_tmp
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE:: pos_below
    DOUBLE PRECISION, DIMENSION(:),   ALLOCATABLE:: nu_below
    CHARACTER( LEN= : ), ALLOCATABLE:: finalnamefile
    LOGICAL:: exist
    IF( MOD(npart_real,2) /= 0 )THEN
      PRINT *, "** ERROR! If the equatorial symmetry has to be imposed, ", &
               "the particle number must be even."
      PRINT *, " * npart_real= ", npart_real
      PRINT *, " * Stopping..."
      PRINT *
      STOP
    ENDIF
    npart_real_old= npart_real
    postmp        = pos
    nutmp = nu
    htmp= h
    nstar_id_tmp= fld% nstar_id
    IF( ALLOCATED(fld% all_pos_prev_dump) ) &
      all_pos_prev_dump_tmp= fld% all_pos_prev_dump
    CALL find_particles_above_xy_plane( npart_real, postmp(:,1:npart_real), &
                                        npart_above_xy, above_xy_plane_a )
    ALLOCATE( pos_below(3,npart_above_xy) )
    ALLOCATE( nu_below(npart_above_xy) )
    CALL reflect_particles_xy_plane( npart_real, postmp(:,1:npart_real), &
                                     pos_below, npart_above_xy, &
                                     above_xy_plane_a, nutmp(1:npart_real), &
                                     nu_below )
    !ELSE
    !
    !  CALL reflect_particles_xy_plane( npart_real, postmp(:,1:npart_real), &
    !                                   pos_below, npart_above_xy, &
    !                                   above_xy_plane_a )
    !
    !ENDIF
    IF( npart_real/2 /= npart_above_xy )THEN
      npart_real= 2*npart_above_xy
      npart_all= npart_real + npart_ghost
      DEALLOCATE(pos)
      ALLOCATE( pos(3,npart_all) )
      DEALLOCATE(nu)
      ALLOCATE( nu(npart_all) )
      CALL fld% reallocate_apm_fields( npart_real, npart_ghost )
!      IF(ALLOCATED(nstar_real)) DEALLOCATE(nstar_real)
!      IF(ALLOCATED(nstar_p)) DEALLOCATE(nstar_p)
!      IF(ALLOCATED(art_pr)) DEALLOCATE(art_pr)
!      IF(ALLOCATED(dNstar)) DEALLOCATE(dNstar)
!      IF(ALLOCATED(nu_tmp)) DEALLOCATE(nu_tmp)
!      !IF(ALLOCATED(dN)) DEALLOCATE(dN)
!      IF(ALLOCATED(good_rho)) DEALLOCATE(good_rho)
!      !IF(ALLOCATED(freeze)) DEALLOCATE(freeze)
!      IF(ALLOCATED(correction_pos)) DEALLOCATE(correction_pos)
!      !IF(ALLOCATED(all_pos_tmp)) DEALLOCATE(all_pos_tmp)
!      !IF(ALLOCATED(all_pos_prev)) DEALLOCATE(all_pos_prev)
!      IF(ALLOCATED(all_pos_prev_dump)) DEALLOCATE(all_pos_prev_dump)
!      IF(ALLOCATED(cnt_move)) DEALLOCATE(cnt_move)
!
!      ALLOCATE(nstar_real(npart_all))
!      ALLOCATE(nstar_p(npart_all))
!      ALLOCATE(art_pr(npart_all))
!      !ALLOCATE(freeze(npart_all))
!      ALLOCATE(correction_pos(3, npart_all))
!      !ALLOCATE(all_pos_tmp(3, npart_all))
!      !ALLOCATE(all_pos_prev(3, npart_all))
!      ALLOCATE(all_pos_prev_dump(3, npart_all))
!
!      ALLOCATE(cnt_move(npart_real))
!      ALLOCATE(dNstar(npart_real))
!      ALLOCATE(nu_tmp(npart_real))
!      !ALLOCATE(dN(npart_real))
!      ALLOCATE(good_rho(npart_real))
!      !all_pos_prev     = -one
!      all_pos_prev_dump= zero
!      cnt_move= 0
! !     !$OMP PARALLEL DO DEFAULT(NONE) &
! !     !$OMP             SHARED(npart_real, freeze) &
! !     !$OMP             PRIVATE(a)
! !     DO a= 1, npart_real, 1
! !       freeze(a)= 0
! !     ENDDO
! !     !$OMP END PARALLEL DO
! !     !$OMP PARALLEL DO DEFAULT(NONE) &
! !     !$OMP             SHARED(npart_real, npart_all, freeze) &
! !     !$OMP             PRIVATE(a)
! !     DO a= npart_real + 1, npart_all , 1
! !       freeze(a)= 1
! !     ENDDO
! !     !$OMP END PARALLEL DO
      npart= npart_all
      IF( ALLOCATED(posmash) ) DEALLOCATE(posmash)
      CALL deallocate_metric_on_particles
      CALL deallocate_gradient
      CALL deallocate_RCB_tree_memory_3D
      CALL deallocate_SPH_memory
      CALL allocate_SPH_memory
      CALL allocate_RCB_tree_memory_3D(npart_all)
      iorig(1:npart_all)= (/ (a,a=1,npart_all) /)
      CALL allocate_gradient(npart_all)
      CALL allocate_metric_on_particles(npart_all)
    ENDIF
    !$OMP PARALLEL DO DEFAULT( NONE ) &
    !$OMP             SHARED( pos, npart_above_xy, nu, postmp, nutmp, &
    !$OMP                     pos_below, nu_below, h, htmp, above_xy_plane_a, &
    !$OMP                     fld, all_pos_prev_dump_tmp, &
    !$OMP                     nstar_id_tmp ) &
    !$OMP             PRIVATE( a )
    DO a= 1, npart_above_xy, 1
      pos( :, a )= postmp( :, a )
      pos( :, npart_above_xy + a )       = pos_below( :, a )
      h( a )                             = htmp( above_xy_plane_a(a) )
      h( npart_above_xy + a )            = htmp( above_xy_plane_a(a) )
      fld% nstar_id( a )                 = nstar_id_tmp( above_xy_plane_a(a) )
      fld% nstar_id( npart_above_xy + a )= nstar_id_tmp( above_xy_plane_a(a) )
      IF( ALLOCATED(fld% all_pos_prev_dump) )THEN
        fld% all_pos_prev_dump(1,a)= &
                                all_pos_prev_dump_tmp(1,above_xy_plane_a(a))
        fld% all_pos_prev_dump(2,a)= &
                                all_pos_prev_dump_tmp(2,above_xy_plane_a(a))
        fld% all_pos_prev_dump(3,a)= &
                                all_pos_prev_dump_tmp(3,above_xy_plane_a(a))
        fld% all_pos_prev_dump(1,npart_above_xy + a)= &
                                all_pos_prev_dump_tmp(1,above_xy_plane_a(a))
        fld% all_pos_prev_dump(2,npart_above_xy + a)= &
                                all_pos_prev_dump_tmp(2,above_xy_plane_a(a))
        fld% all_pos_prev_dump(3,npart_above_xy + a)= &
                              - all_pos_prev_dump_tmp(3,above_xy_plane_a(a))
      ENDIF
      nu( a )= nutmp( a )
      nu( npart_above_xy + a )= nu_below( a )
    ENDDO
    !$OMP END PARALLEL DO
    !$OMP PARALLEL DO DEFAULT( NONE ) &
    !$OMP             SHARED( pos, npart_real, npart_all, nu, postmp, nutmp, &
    !$OMP                     npart_real_old, npart_ghost, h, htmp, &
    !$OMP                     fld, all_pos_prev_dump_tmp, &
    !$OMP                     nstar_id_tmp ) &
    !$OMP             PRIVATE( a )
    DO a= 1, npart_ghost, 1
      pos( :, npart_real + a ) = postmp( :, npart_real_old + a )
      nu( a )= nutmp( npart_real_old + a )
      h( a )= h_fac*htmp( npart_real_old + a )
      fld% nstar_id( a )= nstar_id_tmp( npart_real_old + a )
      IF( ALLOCATED(fld% all_pos_prev_dump) )THEN
        fld% all_pos_prev_dump( :, npart_real + a )= &
                                all_pos_prev_dump_tmp( :, npart_real_old + a )
      ENDIF
    ENDDO
    !$OMP END PARALLEL DO
    IF( PRESENT(verbose) .AND. verbose .EQV. .TRUE. )THEN
      CALL COM( npart_real, pos(:,1:npart_real), nu(1:npart_real), & ! input
                com_x, com_y, com_z, com_d ) ! output
      PRINT *, "** After mirroring particles:"
      IF( PRESENT(com_star) ) PRINT *, &
               " * x coordinate of the center of mass of the star, ", &
               "from LORENE: com_star= ", com_star, "Msun_geo"
      PRINT *, " * x coordinate of the center of mass of the particle ", &
               "distribution: com_x= ", com_x, "Msun_geo"
      PRINT *, " * y coordinate of the center of mass of the particle ", &
               "distribution: com_y= ", com_y, "Msun_geo"
      PRINT *, " * z coordinate of the center of mass of the particle ", &
               "distribution: com_z= ", com_z, "Msun_geo"
      PRINT *, " * Distance of the center of mass of the particle ", &
               "distribution from the  origin: com_d= ", com_d
      IF( PRESENT(com_star) ) PRINT *, " * |com_x-com_star/com_star|=", &
               ABS( com_x-com_star )/ABS( com_star + 1 )
      PRINT *
    ENDIF
  END SUBROUTINE impose_equatorial_plane_symmetry_apm
Call graph
impose_equatorial_plane_symmetry_apm calls com, deallocate_sph_memory, h, iorig, reflect_particles_xy_plane, allocate_sph_memory, deallocate_gradient, allocate_rcb_tree_memory_3d, allocate_metric_on_particles, allocate_gradient, deallocate_rcb_tree_memory_3d, find_particles_above_xy_plane, deallocate_metric_on_particles
reflect_particles_xy_plane calls reflect_particles_xy_plane
find_particles_above_xy_plane calls find_particles_above_xy_plane
perform_apm calls impose_equatorial_plane_symmetry_apm, perform_apm