import_id_params – SPHINCS_LORENE
import_id_params Module Procedure
GNU Free Documentation License
91 statements
Source File
module procedure import_id_params module module subroutine import_id_params(THIS) Interface →
Uses
constants
iso_c_binding
Store the parameters of the binary neutron stars' \(\texttt{LORENE}\) ID into member variables
FT 5.10.2020
Arguments
Type Intent Optional Attributes Name
class(bnslorene), intent(inout) :: THIS
bnslorene object which this PROCEDURE is a member of
Calls
Called by
Contents
Variables
eos1_tmp_c eos2_tmp_c i nchars str_length
Variables
Type Visibility Attributes Name Initial
character(kind=C_CHAR), private, DIMENSION(str_length) :: eos1_tmp_c
character(kind=C_CHAR), private, DIMENSION(str_length) :: eos2_tmp_c
integer, private :: i
integer, private :: nchars
integer, private, parameter :: str_length = 100
Call graph
import_id_params calls print_id_params, get_lorene_id_params, k_lorene2hydrobase_piecewisepolytrope, k_lorene2hydrobase, import_id_params
print_id_params calls print_id_params, k_lorene2hydrobase
construct_bnslorene calls import_id_params, construct_bnslorene
bnslorene calls construct_bnslorene
convergence_test calls bnslorene