interpolate_mass_density – SPHINCS_ID
interpolate_mass_density Module Procedure
16 statements
Source File
module procedure interpolate_mass_density module module function interpolate_mass_density(THIS, x, y, z) result(res) Interface →
Uses
constants
numerics
utility
Returns the mass density at the point given as argument, in units of .
FT 19.11.2021
Arguments
Type Intent Optional Attributes Name
class(ejecta), intent(in) :: THIS
ejecta object which this PROCEDURE is a member of
double precision, intent(in), VALUE :: x
coordinate of the desired point
double precision, intent(in), VALUE :: y
coordinate of the desired point
double precision, intent(in), VALUE :: z
coordinate of the desired point
Return Value double precision
Baryon mass density at
Calls
Called by
Contents
Variables
c0 c00 c000 c001 c01 c010 c011 c1 c10 c100 c101 c11 c110 c111 i ierr j k phi r sgn_z theta x0 x1 x_ell xd y0 y1 y_ell yd z0 z1 z_ell zd zp
Variables
Type Visibility Attributes Name Initial
double precision, private :: c0
double precision, private :: c00
double precision, private :: c000
double precision, private :: c001
double precision, private :: c01
double precision, private :: c010
double precision, private :: c011
double precision, private :: c1
double precision, private :: c10
double precision, private :: c100
double precision, private :: c101
double precision, private :: c11
double precision, private :: c110
double precision, private :: c111
integer, private :: i
integer, private :: ierr
integer, private :: j
integer, private :: k
double precision, private :: phi
double precision, private :: r
integer, private :: sgn_z
double precision, private :: theta
double precision, private :: x0
double precision, private :: x1
double precision, private :: x_ell
double precision, private :: xd
double precision, private :: y0
double precision, private :: y1
double precision, private :: y_ell
double precision, private :: yd
double precision, private :: z0
double precision, private :: z1
double precision, private :: z_ell
double precision, private :: zd
double precision, private :: zp
Call graph
interpolate_mass_density calls trilinear_interpolation, spherical_from_cartesian, interpolate_mass_density