integrate_baryon_mass_density – SPHINCS_ID
integrate_baryon_mass_density Procedure
60 statements
Source File
module procedure integrate_baryon_mass_density module procedure integrate_baryon_mass_density()
Uses
NR
constants
Perform 3D integration over a spherical grid of the baryon mass density. Output baryon mass and radial mass profile.
FT 19.02.2021
Arguments
None
Calls
Contents
Variables
baryon_density colat debug g_xx gamma_euler long mass_element phi r rad_coord sq_g th
Variables
Type Visibility Attributes Name Initial
double precision, private :: baryon_density
double precision, private :: colat
logical, private, parameter :: debug = .TRUE.
double precision, private :: g_xx
double precision, private :: gamma_euler
double precision, private :: long
double precision, private :: mass_element
integer, private :: phi
integer, private :: r
double precision, private :: rad_coord
double precision, private :: sq_g
integer, private :: th
Call graph
integrate_baryon_mass_density calls indexx, mass_profile_idx, mass_profile