integrate_baryon_mass_density – SPHINCS_ID
integrate_baryon_mass_density Module Procedure
50 statements
Source File
module procedure integrate_baryon_mass_density module module subroutine integrate_baryon_mass_density(this, center, radius, central_density, dr, dth, dphi, mass, mass_profile, mass_profile_idx) Interface →
Uses
tensor
NR
utility
constants
Perform 3D integration over a spherical grid of the baryon mass density. Output baryon mass and radial mass profile.
FT 19.02.2021
Arguments
Type Intent Optional Attributes Name
class(idbase), intent(inout) :: this
Object of class idbase which this PROCEDURE is a member of
double precision, intent(in) :: center
Center of the star
double precision, intent(in) :: radius
Radius of the star
double precision, intent(in) :: central_density
Central density of the star
double precision, intent(in) :: dr
Integration steps
double precision, intent(in) :: dth
Integration steps
double precision, intent(in) :: dphi
Integration steps
double precision, intent(inout) :: mass
Integrated mass of the star
double precision, intent(out), DIMENSION(3,0:NINT(radius/dr)) :: mass_profile
Array storing the radial mass profile of the star
integer, intent(out), DIMENSION(0:NINT(radius/dr)) :: mass_profile_idx
Array to store the indices for array mass_profile, sorted so that mass_profile[mass_profile_idx] is in increasing order INTEGER, DIMENSION(:), ALLOCATABLE, INTENT(INOUT):: mass_profile_idx
Calls
Called by
Contents
Variables
baryon_density colat g gamma_euler long mass_element phi r rad_coord sq_g th
Variables
Type Visibility Attributes Name Initial
double precision, private :: baryon_density
double precision, private :: colat
double precision, private, DIMENSION(6) :: g
double precision, private :: gamma_euler
double precision, private :: long
double precision, private :: mass_element
integer, private :: phi
integer, private :: r
double precision, private :: rad_coord
double precision, private :: sq_g
integer, private :: th
Call graph
integrate_baryon_mass_density calls indexx, determinant_sym3x3, integrate_baryon_mass_density