invert_sym4x4 – SPHINCS_ID
invert_sym4x4 Subroutine
17 statements
Source File
public subroutine invert_sym4x4(A, iA)
Uses
matrix
metric_on_particles
tensor
Invert a symemtric matrix stored as a -vector
Note
The inverse (and the adjugate) of a symmetric matrix is symmetric
FT 25.04.2022
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: A(:)
The symmetric matrix, given as a 10-vector. The first 3 components run over the numbers of grid points along each axis. The fourth index runs over the number of independent components of the symmetric matrix.
double precision, intent(out) :: iA(n_sym4x4)
Inverse of the symmetric matrix, given as input.
Calls
Contents
Variables
Amat iAmat
Source Code
invert_sym4x4
Variables
Type Visibility Attributes Name Initial
double precision, public :: Amat(4,4)
The symmetric matrix as a matrix
double precision, public :: iAmat(4,4)
The inverse of the symmetric matrix, as a matrix
Source Code
  SUBROUTINE invert_sym4x4( A, iA )
    !****************************************************************
    !
    !# Invert a \(4\times 4\) symemtric matrix stored as a \(10\)-vector
    !  @note The inverse (and the adjugate) of a symmetric matrix
    !        is symmetric
    !
    !  FT 25.04.2022
    !
    !****************************************************************
    USE tensor,               ONLY: n_sym4x4
    USE metric_on_particles,  ONLY: gvec2mat, mat2gvec
    USE matrix,               ONLY: invert_4x4_matrix
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN):: A(:)
    !# The \(4\times 4\) symmetric matrix, given as a 10-vector.
    !  The first 3 components run over the numbers of grid points
    !  along each axis. The fourth index runs over the number of
    !  independent components of the \(4\times 4\) symmetric matrix.
    DOUBLE PRECISION, INTENT(OUT):: iA(n_sym4x4)
    !# Inverse of the \(4\times 4\) symmetric matrix, given as input.
    DOUBLE PRECISION:: Amat(4,4)
    !! The \(4\times 4\) symmetric matrix as a matrix
    DOUBLE PRECISION:: iAmat(4,4)
    !! The inverse of the \(4\times 4\) symmetric matrix, as a matrix
    IF( SIZE(A) /= n_sym4x4 )THEN
      PRINT *, "** ERROR in determinant_sym4x4_grid in MODULE utility.", &
               " This subroutine needs a symmetric matrix with 10 components,",&
               " and a ", SIZE(A), "component matrix was given instead."
      STOP
    ENDIF
    CALL gvec2mat(A,Amat)
    CALL invert_4x4_matrix(Amat,iAmat)
    CALL mat2gvec(iA,iAmat)
  END SUBROUTINE invert_sym4x4
Call graph
invert_sym4x4 calls gvec2mat, invert_4x4_matrix, mat2gvec