is_finite_number – SPHINCS_ID
is_finite_number Function
6 statements
Source File
public pure function is_finite_number(x) result(res)
Uses
ieee_arithmetic
Test if a double precision is a finite number
FT 11.02.2022
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
Return Value logical
Called by
Contents
Source Code
is_finite_number
Source Code
  PURE FUNCTION is_finite_number( x ) RESULT( res )
    !***********************************************
    !
    !# Test if a double precision is a finite number
    !
    !  FT 11.02.2022
    !
    !***********************************************
    USE, INTRINSIC:: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
    DOUBLE PRECISION, INTENT(IN):: x
    LOGICAL:: res
    res= (.NOT.ISNAN(x)) .AND. IEEE_IS_FINITE(x)
  END FUNCTION is_finite_number
Call graph
read_fuka_id_spacetime calls is_finite_number, read_fuka_id_spacetime
compute_adm_momentum_fluid_m2p calls is_finite_number, compute_adm_momentum_fluid_m2p
correct_center_of_mass calls is_finite_number, correct_center_of_mass
read_fuka_id_particles calls is_finite_number, read_fuka_id_particles
number_surfaces calls is_finite_number
perform_apm calls is_finite_number, get_nstar_id_atm, correct_center_of_mass, perform_apm
compute_and_print_bssn_variables calls check_bssn_id_for_nans, compute_and_print_bssn_variables
place_particles_spherical_surfaces calls number_surfaces, place_particles_spherical_surfaces
construct_particles_std calls correct_center_of_mass, construct_particles_std
particles calls construct_particles_std
sphincs_id calls particles
convergence_test calls particles