k_lorene2hydrobase – SPHINCS_ID
k_lorene2hydrobase Function
5 statements
Source File
public function k_lorene2hydrobase(gamma)
Arguments
Type Intent Optional Attributes Name
double precision :: gamma
Return Value double precision
Called by
Contents
None
Call graph
write_par_eos calls k_lorene2hydrobase
import_id_params calls k_lorene2hydrobase, print_id_params, import_id_params
print_id_params calls k_lorene2hydrobase, print_id_params
print_diffstar_params calls k_lorene2hydrobase, print_diffstar_params
import_diffstar_params calls k_lorene2hydrobase, print_diffstar_params, import_diffstar_params
construct_bnslorene calls import_id_params, construct_bnslorene
construct_diffstarlorene calls import_diffstar_params, construct_diffstarlorene