perform_apm – SPHINCS_ID
perform_apm Module Procedure
1413 statements
Source File
module procedure perform_apm module module subroutine perform_apm(this, get_density, get_nstar_id, npart_output, pos_input, pvol, h_output, nu_output, center, com_star, mass, sizes, apm_max_it, max_inc, mass_it, correct_nu, nuratio_thres, nuratio_des, nx_gh, ny_gh, nz_gh, ghost_dist, use_atmosphere, remove_atmosphere, print_step, namefile_pos_id, namefile_pos, namefile_results, validate_position) Interface →
Uses
constants
metric_on_particles
sphincs_sph
set_h
APM
gradient
matrix
utility
sph_variables
units
analyze
kernel_table
RCB_tree_3D
Compute the particle positions as follows:
Take initial particle distribution as input
Assume that the particles have the same mass
Do the APM iteration so that the final SPH kernel estimate of the baryon mass density matches the baryon density in the given \(\mathrm{ID}\)
Correct the particle masses ONCE, in order to match the density even better. Since we don't want a large mass ratio, we impose a maximum mass ratio when performing this correction.
After this procedure, the resulting particle distribution has positions and baryon numbers that kernel-estimate very well the mass density of the star, and has a low mass ratio.
This procedure assigns positions, smoothing lengths , and .
Warning
If the outer layers of a star have a very low density compared to the core, it can happen that, irrespective of the initial particle distribution and the APM parameters, the particle distribution output by the APM does not have a smooth surface. In this case, the only solution (that has been found as of 20.10.2021) is to increase the particle number.
As of 20.10.2021, this has only happened with the CompOSE tabulated EOS (all of them), but not with any piecewise polytropic or polytropic EOS.
This problem can manifest itself with error messages concerning particles occupying the sameposition, or some smoothing lengths being 0, or a matrix not being invertible.
FT 20.10.2021
FT 04.06.2021
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
function get_density(x, y, z) result(density)
Returns the baryon mass density at the desired point
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value double precision
Baryon mass density at
subroutine get_nstar_id(npart, x, y, z, nstar_sph, nstar_id, nlrf_sph, sqg)
Computes the proper baryon number density at the particle positions
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
Number of real particles (i.e., no ghost particles included here)
double precision, intent(in) :: x(npart)
Array of coordinates
double precision, intent(in) :: y(npart)
Array of coordinates
double precision, intent(in) :: z(npart)
Array of coordinates
double precision, intent(in) :: nstar_sph(npart)
\(\mathrm{SPH}\) proper baryon density
double precision, intent(out) :: nstar_id(npart)
Array to store the computed proper baryon number density
double precision, intent(out) :: nlrf_sph(npart)
Array to store the local rest frame baryon density computed from the \(\mathrm{SPH}\) proper baryon density
double precision, intent(out) :: sqg(npart)
Square root of minus the determinant of the spacetime metric
integer, intent(inout) :: npart_output
Initial particle number
double precision, intent(inout), DIMENSION(:,:), ALLOCATABLE :: pos_input
Initial particle positions
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: pvol
Initial particle volume
double precision, intent(out), DIMENSION(:), ALLOCATABLE :: h_output
Array to store the smoothing lengths computed at the end of the APM iteration
double precision, intent(out), DIMENSION(:), ALLOCATABLE :: nu_output
Array to store the baryon number per particle computed at the end of the APM iteration
double precision, intent(in), DIMENSION(3) :: center
Center of the star (point of highest density), computed by \(\texttt{LORENE}\)
double precision, intent(inout), DIMENSION(3) :: com_star
Center of mass of the star, computed by \(\texttt{LORENE}\)
double precision, intent(in) :: mass
Mass of the star
double precision, intent(in), DIMENSION(6) :: sizes
Radius of the star in the x direction, towards the companion
integer, intent(in) :: apm_max_it
Maximum number of APM iterations, irrespective of the EXIT condition
integer, intent(in) :: max_inc
Sets the EXIT condition: If the average over all the particles of the relative error in the density estimate grows max_inc times, exit the iteration.
logical, intent(in) :: mass_it
If .TRUE. performs a second iteration after the APM one, without moving the particles, changing their mass in order to better match the star density. The mass ratio grows very fast in all the tried experiments, hence the suggested value is .FALSE.
logical, intent(in) :: correct_nu
If .TRUE., the baryon number per particle nu is corrected to include the total baryonic masses of the stars.
double precision, intent(in) :: nuratio_thres
Maximum mass ratio (equivalently baryon number ratio) to be used in the one-time-only final correction of the particle masses to match the star density even better (without moving the particles)
double precision, intent(in) :: nuratio_des
Sets the EXIT condition: If the baryon number ratio is within 2.5% of nuratio_des, exit the iteration Set nuratio_des to 0 to deactivate and exit the APM iteration using max_inc
integer, intent(in) :: nx_gh
Number of lattice points in the x direction for ghosts
integer, intent(in) :: ny_gh
Number of lattice points in the y direction for ghosts
integer, intent(in) :: nz_gh
Number of lattice points in the z direction for ghosts
double precision, intent(in) :: ghost_dist
Distance between the ghost particles and the surface of the matter object considered (star, ejecta, etc...)
logical, intent(inout) :: use_atmosphere
If .TRUE., allows particles to move where the density is 0, and displace them using only the smoothing term. This can be useful when the system has an irregular geometry, as, for example, an ejecta; .FALSE. otherwise
logical, intent(inout) :: remove_atmosphere
If .TRUE., removes the particles placed where the density is 0, at the end of the APM iteration; .FALSE. otherwise
integer, intent(inout) :: print_step
Prints the particle positions to a formatted file every print_step steps
character(len=*), intent(inout), optional :: namefile_pos_id
Name for the formatted file where the initial particle positions and the ghost positions will be printed
character(len=*), intent(inout), optional :: namefile_pos
Name for the formatted file where the particle positions and the ghost positions will be printed every 15 iterations
character(len=*), intent(inout), optional :: namefile_results
Name for the formatted file where various quantities related to the particle distribution, the baryon number particle and the kernel estimate of the density will be printed at the end of the APM iteration
procedure(validate_position_int), optional :: validate_position
Returns 1 if the position is not valid, 0 otherwise
Calls
Called by
Contents
Variables
Wa Wab_ha Wi Wi1 a a_numax a_numax2 a_numin a_numin2 all_pos all_pos_prev art_pr art_pr_max atmosphere_density b cnt1 cnt_move com_d com_x com_y com_z correction_pos dN dN_av dN_max dNstar dS debug dens_min dim_seed dvv dx dy dz eab ellipse_thickness eps err_N_max err_N_mean err_N_mean_min err_N_mean_min_old err_mean_old err_n_min exist few_ncand finalnamefile find_h_bruteforce_timer ghost_pos grW grW_ha_x grW_ha_y grW_ha_z grW_hb_x grW_hb_y grW_hb_z grWa grWb h_av h_guess h_guess_tmp h_max h_tmp ha ha2 ha2_4 ha_1 ha_3 ha_4 hb hb2_4 hb_1 hb_3 hb_4 i ill inde index1 itot itr itr2 j k l larger_radius m_max_it max_art_pr_ghost max_npart max_nu max_nu2 max_r_real max_z_real mean_nu min_nu min_nu2 multiple_h_av n_inc n_neighbors n_problematic_h nearest_neighbors neighbors_lists nlrf_sph nn_des npart_all npart_ghost npart_real npart_real_half nstar_id nstar_id_err nstar_int nstar_sph nstar_sph_err nu_all nu_one nu_ratio nu_tmp nu_tmp2 nu_tot nuratio_cnt nuratio_max_steps nuratio_min_it nuratio_tmp nuratio_tmp_prev nuratio_tol nx ny nz particle_density_final phi phi_ell pos pos_corr_tmp pos_maxerr pos_tmp pr_sph prgNa prgNb pvol_tmp r r_ell r_real rab rab2 rab_1 rad_x rad_y rad_z radius_y radius_z rand_num rand_num2 rel_sign rho_tmp search_pos seed smaller_radius sqg stddev_dN stddev_nu theta theta_ell tiny_real tmp tol va variance_dN variance_nu vb x_ell xa xb xmax xmin xtemp y_ell ya yb ymax ymin ytemp z_ell za zb zmax zmin ztemp
Functions
validate_position_final
Subroutines
allocate_apm_fields compute_hydro_momentum discard_atmosphere dump_apm_pos get_nstar_id_atm place_and_print_ghost_particles reallocate_output_fields
Variables
Type Visibility Attributes Name Initial
double precision, private :: Wa
double precision, private :: Wab_ha
double precision, private :: Wi
double precision, private :: Wi1
integer, private :: a
integer, private :: a_numax
integer, private :: a_numax2
integer, private :: a_numin
integer, private :: a_numin2
double precision, private, DIMENSION(:,:), ALLOCATABLE :: all_pos
double precision, private, DIMENSION(:,:), ALLOCATABLE :: all_pos_prev
double precision, private, DIMENSION(:), ALLOCATABLE :: art_pr
double precision, private :: art_pr_max
double precision, private :: atmosphere_density
integer, private :: b
integer, private :: cnt1
integer, private, DIMENSION(:), ALLOCATABLE :: cnt_move
double precision, private :: com_d
double precision, private :: com_x
double precision, private :: com_y
double precision, private :: com_z
double precision, private, DIMENSION(:,:), ALLOCATABLE :: correction_pos
double precision, private :: dN
double precision, private :: dN_av
double precision, private :: dN_max
double precision, private, DIMENSION(:), ALLOCATABLE :: dNstar
double precision, private, DIMENSION(:,:), ALLOCATABLE :: dS
logical, private, parameter :: debug = .FALSE.
double precision, private :: dens_min
integer, private :: dim_seed
double precision, private :: dvv
double precision, private :: dx
double precision, private :: dy
double precision, private :: dz
double precision, private :: eab(3)
double precision, private, parameter :: ellipse_thickness = 1.1D0
double precision, private, parameter :: eps = 5.0D-1
double precision, private :: err_N_max
double precision, private :: err_N_mean
double precision, private :: err_N_mean_min
double precision, private :: err_N_mean_min_old
double precision, private :: err_mean_old
double precision, private :: err_n_min
logical, private :: exist
logical, private :: few_ncand
character(len=:), private, ALLOCATABLE :: finalnamefile
type(timer), private :: find_h_bruteforce_timer
double precision, private, DIMENSION(:,:), ALLOCATABLE :: ghost_pos
double precision, private :: grW
double precision, private :: grW_ha_x
double precision, private :: grW_ha_y
double precision, private :: grW_ha_z
double precision, private :: grW_hb_x
double precision, private :: grW_hb_y
double precision, private :: grW_hb_z
double precision, private :: grWa
double precision, private :: grWb
double precision, private :: h_av
double precision, private, DIMENSION(:), ALLOCATABLE :: h_guess
double precision, private, DIMENSION(:), ALLOCATABLE :: h_guess_tmp
double precision, private :: h_max
double precision, private, DIMENSION(:), ALLOCATABLE :: h_tmp
double precision, private :: ha
double precision, private :: ha2
double precision, private :: ha2_4
double precision, private :: ha_1
double precision, private :: ha_3
double precision, private :: ha_4
double precision, private :: hb
double precision, private :: hb2_4
double precision, private :: hb_1
double precision, private :: hb_3
double precision, private :: hb_4
integer, private :: i
integer, private :: ill
integer, private :: inde
integer, private :: index1
integer, private :: itot
integer, private :: itr
integer, private :: itr2
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private :: larger_radius
integer, private, parameter :: m_max_it = 50
double precision, private, parameter :: max_art_pr_ghost = 1.0D+10
integer, private, parameter :: max_npart = 10D+6
double precision, private :: max_nu
double precision, private :: max_nu2
double precision, private :: max_r_real
double precision, private :: max_z_real
double precision, private :: mean_nu
double precision, private :: min_nu
double precision, private :: min_nu2
double precision, private, parameter :: multiple_h_av = 1.0D0
integer, private :: n_inc
integer, private, DIMENSION(:), ALLOCATABLE :: n_neighbors
integer, private :: n_problematic_h
double precision, private, DIMENSION(:,:), ALLOCATABLE :: nearest_neighbors
integer, private, DIMENSION(:), ALLOCATABLE :: neighbors_lists
double precision, private, DIMENSION(:), ALLOCATABLE :: nlrf_sph
integer, private, parameter :: nn_des = 301
integer, private :: npart_all
integer, private :: npart_ghost
integer, private :: npart_real
integer, private :: npart_real_half
double precision, private, DIMENSION(:), ALLOCATABLE :: nstar_id
double precision, private :: nstar_id_err
double precision, private, DIMENSION(:), ALLOCATABLE :: nstar_int
double precision, private, DIMENSION(:), ALLOCATABLE :: nstar_sph
double precision, private :: nstar_sph_err
double precision, private :: nu_all
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_one
double precision, private :: nu_ratio
double precision, private, DIMENSION(:), ALLOCATABLE :: nu_tmp
double precision, private :: nu_tmp2
double precision, private :: nu_tot
integer, private :: nuratio_cnt
integer, private, parameter :: nuratio_max_steps = 50
integer, private, parameter :: nuratio_min_it = 100
double precision, private :: nuratio_tmp
double precision, private :: nuratio_tmp_prev
double precision, private, parameter :: nuratio_tol = 0.0025
integer, private :: nx
integer, private :: ny
integer, private :: nz
double precision, private, DIMENSION(:), ALLOCATABLE :: particle_density_final
double precision, private :: phi
double precision, private :: phi_ell
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos
double precision, private, DIMENSION(3) :: pos_corr_tmp
double precision, private, DIMENSION(3) :: pos_maxerr
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos_tmp
double precision, private, DIMENSION(:), ALLOCATABLE :: pr_sph
double precision, private :: prgNa
double precision, private :: prgNb
double precision, private, DIMENSION(:), ALLOCATABLE :: pvol_tmp
double precision, private :: r
double precision, private :: r_ell
double precision, private :: r_real
double precision, private :: rab
double precision, private :: rab2
double precision, private :: rab_1
double precision, private :: rad_x
double precision, private :: rad_y
double precision, private :: rad_z
double precision, private :: radius_y
double precision, private :: radius_z
double precision, private :: rand_num
double precision, private :: rand_num2
integer, private :: rel_sign
double precision, private, DIMENSION(:), ALLOCATABLE :: rho_tmp
integer, private, parameter :: search_pos = 10
integer, private, DIMENSION(:), ALLOCATABLE :: seed
double precision, private :: smaller_radius
double precision, private, DIMENSION(:), ALLOCATABLE :: sqg
double precision, private :: stddev_dN
double precision, private :: stddev_nu
double precision, private :: theta
double precision, private :: theta_ell
double precision, private, parameter :: tiny_real = 1.0D-10
double precision, private :: tmp
double precision, private, parameter :: tol = 1.0D-3
double precision, private :: va
double precision, private :: variance_dN
double precision, private :: variance_nu
double precision, private :: vb
double precision, private :: x_ell
double precision, private :: xa
double precision, private :: xb
double precision, private :: xmax
double precision, private :: xmin
double precision, private :: xtemp
double precision, private :: y_ell
double precision, private :: ya
double precision, private :: yb
double precision, private :: ymax
double precision, private :: ymin
double precision, private :: ytemp
double precision, private :: z_ell
double precision, private :: za
double precision, private :: zb
double precision, private :: zmax
double precision, private :: zmin
double precision, private :: ztemp
Functions
function validate_position_final(x, y, z) result(answer)
Returns validate_position(x, y, z) if the latter is present, 0 otherwise
FT 22.09.2021
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value logical
validate_position(x, y, z) if the latter is present, 0 otherwise
Subroutines
subroutine allocate_apm_fields(npart_real, npart_ghost)
Allocate the fields used during the APM iteration
FT 20.04.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
integer, intent(in) :: npart_ghost
subroutine compute_hydro_momentum()
FT 17.06.2022
Arguments
None
subroutine discard_atmosphere(npart_real)
Remove the atmosphere
FT 20.04.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: npart_real
subroutine dump_apm_pos()
Print the positions of the real and ghost particles to a formatted file
FT 20.04.2022
Arguments
None
subroutine get_nstar_id_atm(npart_real, x, y, z, nstar_sph, nstar_id, nlrf_sph, sqg, use_atmosphere)
FT 5.12.2021
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
Number of real particles (i.e., no ghost particles included here)
double precision, intent(in) :: x(npart_real)
Array of coordinates
double precision, intent(in) :: y(npart_real)
Array of coordinates
double precision, intent(in) :: z(npart_real)
Array of coordinates
double precision, intent(in) :: nstar_sph(npart)
\(\mathrm{SPH}\) proper baryon density
double precision, intent(out) :: nstar_id(npart)
Array to store the computed proper baryon number density
double precision, intent(out) :: nlrf_sph(npart)
Array to store the local rest frame baryon density computed from the \(\mathrm{SPH}\) proper baryon density
double precision, intent(out) :: sqg(npart)
Square root of minus the determinant of the sacetime metric DOUBLE PRECISION, INTENT(OUT):: nstar_eul_id(npart_real) Array to store the computed proper baryon number density seen by the Eulerian observer
logical, intent(in) :: use_atmosphere
.TRUE. if an atmosphere should be used during the APM, to allow the real aprticles more freedom to move around and adjust; .FALSE. otherwise
subroutine place_and_print_ghost_particles()
Place ghost particles around the matter object, and print their positions together with the positions of the real particles to a formatted file
FT 20.04.2022
Arguments
None
subroutine reallocate_output_fields(npart_real)
Reallocate the fields to be returned by perform_apm
FT 20.04.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart_real
Call graph
perform_apm calls lpart, impose_equatorial_plane_symmetry, deallocate_sph_memory, deallocate_metric_on_particles, timer, deallocate_rcb_tree_memory_3d, dump_apm_pos, allocate_sph_memory, spherical_from_cartesian, check_particle_positions, nic, density_loop, allocate_gradient, position_correction, discard_atmosphere, nu, ncand, reallocate_output_fields, exact_nei_tree_update, rpart, allocate_metric_on_particles, is_finite_number, find_h_backup, h, correct_center_of_mass, validate_position_final, allocate_apm_fields, place_and_print_ghost_particles, density, com, deallocate_gradient, assign_h, get_nstar_id_atm, allocate_rcb_tree_memory_3d, iorig, perform_apm
impose_equatorial_plane_symmetry calls impose_equatorial_plane_symmetry, com, find_particles_above_xy_plane, reflect_particles_xy_plane
check_particle_positions calls check_particle_positions, indexx
correct_center_of_mass calls correct_center_of_mass, is_finite_number, com
find_particles_above_xy_plane calls find_particles_above_xy_plane
reflect_particles_xy_plane calls reflect_particles_xy_plane