place_particles_spherical_surfaces – SPHINCS_ID
place_particles_spherical_surfaces Module Procedure
830 statements
Source File
module procedure place_particles_spherical_surfaces module module subroutine place_particles_spherical_surfaces(this, mass_star, radius, center, central_density, npart_des, npart_out, pos, pvol, pmass, last_r, upper_bound, lower_bound, upper_factor, lower_factor, max_steps, filename_mass_profile, filename_shells_radii, filename_shells_pos, get_density, integrate_density, get_id, validate_position, pmass_des) Interface →
Uses
matrix
APM
constants
utility
NR
Places particles on spherical surfaces inside a star
FT 19.04.2021
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
double precision, intent(in) :: mass_star
Baryonic mass of the star
double precision, intent(in) :: radius
Radius of the star in the x direction towards the companion
double precision, intent(in) :: center
(x|) coordinate of the center of the star, i.e., of the point with highest density
double precision, intent(in) :: central_density
Central density of the star, i.e., highest density
integer, intent(in) :: npart_des
idbase object needed to access the BNS data
Todo
Remove the idbase argument as done in SUBROUTINE perform_apm CLASS(idbase), INTENT(IN OUT):: id Approximate particle number on the star
integer, intent(out) :: npart_out
Final number of particles on the star
double precision, intent(inout), DIMENSION(:,:), ALLOCATABLE :: pos
Array string the final positions
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: pvol
Array soring the inal particle volumes
double precision, intent(inout), DIMENSION(:), ALLOCATABLE :: pmass
Array storing the final particle masses
double precision, intent(in) :: last_r
Radius of the last spherical surface
double precision, intent(inout) :: upper_bound
Desired upper bound for the differences between particle masses on neighbouring spherical surfaces
double precision, intent(inout) :: lower_bound
Desired lower bound for the differences between particle masses on neighbouring spherical surfaces
double precision, intent(in) :: upper_factor
If, after max_steps, the iteration did not converge, multiply upper_bound by upper_factor, and lower_bound by lower_factor. upper_factor >= 1, usually an increase of 1% works
double precision, intent(in) :: lower_factor
If, after max_steps, the iteration did not converge, multiply upper_bound by upper_factor, and lower_bound by lower_factor. lower_factor <= 1, usually a decrease of 1% works
integer, intent(in) :: max_steps
If, after max_steps, the iteration did not converge, multiply upper_bound by upper_factor, and lower_bound by lower_factor. max_steps >= 10. 100 is a nice value
character(len=*), intent(inout), optional :: filename_mass_profile
Name of the file to store the radial mass profile
character(len=*), intent(inout), optional :: filename_shells_radii
Name of the file to store the surface radii
Todo
change name of variable to filename_surfaces_radii
character(len=*), intent(inout), optional :: filename_shells_pos
Name of the file to store the final particle positions
Todo
change name of variable to filename_surfaces_pos
function get_density(x, y, z) result(density)
Returns the baryon mass density at the desired point
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value double precision
Baryon mass density at
subroutine integrate_density(center, radius, central_density, dr, dth, dphi, mass, mass_profile, mass_profile_idx)
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: center
Center of the star
double precision, intent(in) :: radius
Radius of the star
double precision, intent(in) :: central_density
Central density of the star
double precision, intent(in) :: dr
Integration steps
double precision, intent(in) :: dth
Integration steps
double precision, intent(in) :: dphi
Integration steps
double precision, intent(inout) :: mass
Integrated mass of the star
double precision, intent(out), DIMENSION(3,0:NINT(radius/dr)) :: mass_profile
Array storing the radial mass profile of the star
integer, intent(out), DIMENSION(0:NINT(radius/dr)) :: mass_profile_idx
Array to store the indices for array mass_profile, sorted so that mass_profile[mass_profile_idx] is in increasing order INTEGER, DIMENSION(:), ALLOCATABLE, INTENT(IN OUT)::mass_profile_idx
subroutine get_id(x, y, z, sqdetg, baryon_density, gamma_euler)
Returns the baryon mass density at the desired point
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
double precision, intent(out) :: sqdetg
double precision, intent(out) :: baryon_density
double precision, intent(out) :: gamma_euler
procedure(validate_position_int), optional :: validate_position
Returns 1 if the position is not valid, 0 otherwise
double precision, intent(in), optional :: pmass_des
Calls
Called by
Contents
Variables
alpha bar_density_tmp cnt cnt2 col col_tmp colatitude_pos debug delta_r dim_seed dphi dphi_shells dr dr_shells dth dth_shells exist finalnamefile finalnamefile2 first_r gam_euler_tmp high_mass huge_real i_shell itr2 kept_all long low_mass lower_bound_tmp m_p m_parts mass mass_profile mass_profile_idx mass_surface mass_surface2 mass_test mass_test2 n_surfaces npart_discard npart_discarded npart_shell npart_shell_cnt npart_shell_kept npart_shell_tmp npart_shelleq npart_surface_tmp npart_test phase phase_th phi pos_shell_tmp pos_surfaces prev_shell proper_volume proper_volume_test pvol_tmp r r_cnt rad rand_num rand_num2 rel_sign seed shell_scales shell_thickness size_pos_shell sqdetg_tmp surface_masses surface_radii surface_vol surface_vol2 th upper_bound_tmp xtemp ytemp ztemp
Derived Types
colatitude_pos_shell pos_on_surfaces
Functions
validate_position_final
Subroutines
allocate_surface_memory initialize_surfaces
Variables
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:), ALLOCATABLE :: alpha
double precision, private, DIMENSION(:,:), ALLOCATABLE :: bar_density_tmp
integer, private :: cnt
integer, private :: cnt2
double precision, private :: col
double precision, private :: col_tmp
type(colatitude_pos_shell), private, DIMENSION(:), ALLOCATABLE :: colatitude_pos
logical, private, parameter :: debug = .FALSE.
double precision, private :: delta_r
integer, private :: dim_seed
double precision, private :: dphi
double precision, private :: dphi_shells
double precision, private :: dr
double precision, private :: dr_shells
double precision, private :: dth
double precision, private :: dth_shells
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
character(len=:), private, ALLOCATABLE :: finalnamefile2
integer, private :: first_r
double precision, private, DIMENSION(:,:), ALLOCATABLE :: gam_euler_tmp
logical, private :: high_mass
double precision, private, parameter :: huge_real = 1.0D30
integer, private :: i_shell
integer, private :: itr2
logical, private :: kept_all
double precision, private :: long
logical, private :: low_mass
double precision, private :: lower_bound_tmp
double precision, private :: m_p
double precision, private, DIMENSION(:), ALLOCATABLE :: m_parts
double precision, private :: mass
double precision, private, DIMENSION(:,:), ALLOCATABLE :: mass_profile
integer, private, DIMENSION(:), ALLOCATABLE :: mass_profile_idx
double precision, private, DIMENSION(:), ALLOCATABLE :: mass_surface
double precision, private, DIMENSION(:), ALLOCATABLE :: mass_surface2
double precision, private :: mass_test
double precision, private :: mass_test2
integer, private :: n_surfaces
integer, private :: npart_discard
integer, private, DIMENSION(:,:), ALLOCATABLE :: npart_discarded
integer, private, DIMENSION(:), ALLOCATABLE :: npart_shell
integer, private :: npart_shell_cnt
double precision, private :: npart_shell_kept
integer, private :: npart_shell_tmp
integer, private, DIMENSION(:), ALLOCATABLE :: npart_shelleq
integer, private, DIMENSION(:,:), ALLOCATABLE :: npart_surface_tmp
integer, private :: npart_test
double precision, private :: phase
double precision, private :: phase_th
integer, private :: phi
double precision, private, DIMENSION(:,:,:), ALLOCATABLE :: pos_shell_tmp
type(pos_on_surfaces), private, DIMENSION(:), ALLOCATABLE :: pos_surfaces
integer, private :: prev_shell
double precision, private :: proper_volume
double precision, private :: proper_volume_test
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pvol_tmp
integer, private :: r
integer, private :: r_cnt
double precision, private :: rad
double precision, private :: rand_num
double precision, private :: rand_num2
integer, private :: rel_sign
integer, private, DIMENSION(:), ALLOCATABLE :: seed
double precision, private, DIMENSION(:), ALLOCATABLE :: shell_scales
double precision, private :: shell_thickness
integer, private :: size_pos_shell
double precision, private, DIMENSION(:,:), ALLOCATABLE :: sqdetg_tmp
double precision, private, DIMENSION(:), ALLOCATABLE :: surface_masses
double precision, private, DIMENSION(:), ALLOCATABLE :: surface_radii
double precision, private, DIMENSION(:), ALLOCATABLE :: surface_vol
double precision, private, DIMENSION(:), ALLOCATABLE :: surface_vol2
integer, private :: th
double precision, private :: upper_bound_tmp
double precision, private :: xtemp
double precision, private :: ytemp
double precision, private :: ztemp
Derived Types
type :: colatitude_pos_shell
Components
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:), ALLOCATABLE :: colatitudes
type :: pos_on_surfaces
Components
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:), ALLOCATABLE :: baryon_density
double precision, private, DIMENSION(:), ALLOCATABLE :: gamma_euler
double precision, private, DIMENSION(:), ALLOCATABLE :: pos_phi
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos_shell
double precision, private, DIMENSION(:), ALLOCATABLE :: pos_th
double precision, private, DIMENSION(:), ALLOCATABLE :: psurface_vol
double precision, private, DIMENSION(:), ALLOCATABLE :: psurface_vol2
double precision, private, DIMENSION(:), ALLOCATABLE :: sqdetg
Functions
function validate_position_final(x, y, z) result(answer)
Returns validate_position(x, y, z) if the latter is present, .TRUE. otherwise
FT 22.09.2021
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the desired point
double precision, intent(in) :: y
coordinate of the desired point
double precision, intent(in) :: z
coordinate of the desired point
Return Value logical
validate_position(x, y, z) if the latter is present, .TRUE. otherwise
Subroutines
subroutine allocate_surface_memory()
Allocates memory for the spherical surfaces
FT 21.04.2022
Arguments
None
subroutine initialize_surfaces()
Initializes the fields before the iteration over the surfaces
FT 21.04.2022
Arguments
None
Call graph
place_particles_spherical_surfaces calls particle_volume, reallocate_array_1d, initialize_surfaces, print_mass_profile_surface_radii, place_surfaces, compute_colatitudes_uniformly_in, validate_position_final, assign_surfaces_mass, reallocate_array_2d, allocate_surface_memory, number_surfaces, place_particles_spherical_surfaces
number_surfaces calls is_finite_number