print_id_params – SPHINCS_LORENE
print_id_params Module Procedure
GNU Free Documentation License
107 statements
Source File
module procedure print_id_params module module subroutine print_id_params(THIS) Interface →
Uses
constants
Print the parameters of the binary neutron stars' initial data computed by \(\texttt{LORENE}\)
FT 8.10.2020
Arguments
Type Intent Optional Attributes Name
class(bnslorene), intent(inout) :: THIS
bnslorene object which this PROCEDURE is a member of
Calls
Called by
Contents
None
Call graph
print_id_params calls k_lorene2hydrobase, print_id_params
import_id_params calls print_id_params, import_id_params
construct_bnslorene calls import_id_params, construct_bnslorene
bnslorene calls construct_bnslorene
convergence_test calls bnslorene