print_diffstar_params – SPHINCS_ID
print_diffstar_params Module Procedure
70 statements
Source File
module procedure print_diffstar_params module module subroutine print_diffstar_params(THIS) Interface →
Uses
constants
Print the parameters of the binary neutron stars' initial data computed by \(\texttt{LORENE}\)
FT 8.10.2020
Arguments
Type Intent Optional Attributes Name
class(diffstarlorene), intent(inout) :: THIS
diffstarlorene object which this PROCEDURE is a member of
Calls
Called by
Contents
None
Call graph
print_diffstar_params calls k_lorene2hydrobase, print_diffstar_params
import_diffstar_params calls print_diffstar_params, import_diffstar_params
construct_diffstarlorene calls import_diffstar_params, construct_diffstarlorene