print_formatted_id_bssn_variables – SPHINCS_ID
print_formatted_id_bssn_variables Module Procedure
91 statements
Source File
module procedure print_formatted_id_bssn_variables module module subroutine print_formatted_id_bssn_variables(THIS, namefile) Interface →
Uses
tensor
Print the BSSN ID, computed on the gravity grid, to a formatted file
FT 26.10.2020
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: THIS
bssn object to which this PROCEDURE is bound
character(len=*), intent(inout), optional :: namefile
Calls
Called by
Contents
Variables
exist finalnamefile i j k l min_abs_y min_abs_z min_ix_y min_ix_z min_iy_y min_iy_z min_iz_y min_iz_z
Variables
Type Visibility Attributes Name Initial
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private :: min_abs_y
double precision, private :: min_abs_z
integer, private :: min_ix_y
integer, private :: min_ix_z
integer, private :: min_iy_y
integer, private :: min_iy_z
integer, private :: min_iz_y
integer, private :: min_iz_z
Call graph
print_formatted_id_bssn_variables calls trk, a_bssn3_ll, gamma_u, g_bssn3_ll, lapse, shift_u, phi, print_formatted_id_bssn_variables