read_bssn_dump_print_formatted – SPHINCS_ID
read_bssn_dump_print_formatted Module Procedure
101 statements
Source File
module procedure read_bssn_dump_print_formatted module module subroutine read_bssn_dump_print_formatted(THIS, namefile_bin, namefile) Interface →
Uses
mesh_refinement
tensor
ADM_refine
BSSN_refine
Read the BSSN ID from the binary file output by write_BSSN_dump, and print it to a formatted file
FT 08.02.2021
Arguments
Type Intent Optional Attributes Name
class(bssn), intent(inout) :: THIS
bssn object to which this PROCEDURE is bound
character(len=*), intent(inout), optional :: namefile_bin
character(len=*), intent(inout), optional :: namefile
Calls
Called by
Contents
Variables
exist finalnamefile i j k l min_abs_y min_abs_z min_ix_y min_ix_z min_iy_y min_iy_z min_iz_y min_iz_z
Variables
Type Visibility Attributes Name Initial
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private :: min_abs_y
double precision, private :: min_abs_z
integer, private :: min_ix_y
integer, private :: min_ix_z
integer, private :: min_iy_y
integer, private :: min_iy_z
integer, private :: min_iz_y
integer, private :: min_iz_z
Call graph
read_bssn_dump_print_formatted calls gamma_u, allocate_adm, a_bssn3_ll, read_bssn_dump, lapse, trk, deallocate_adm, shift_u, allocate_bssn, deallocate_bssn, g_bssn3_ll, phi, read_bssn_dump_print_formatted