read_sphincs_dump_print_formatted – SPHINCS_ID
read_sphincs_dump_print_formatted Module Procedure
108 statements
Source File
module procedure read_sphincs_dump_print_formatted module module subroutine read_sphincs_dump_print_formatted(this, namefile_bin, namefile, save_data) Interface →
Uses
constants
alive_flag
input_output
sph_variables
Read the SPH ID from the binary file output by write_SPHINCS_dump, and print it to a formatted file
FT 12.02.2021
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
character(len=*), intent(inout), optional :: namefile_bin
Name of the binary file to be read
character(len=*), intent(inout), optional :: namefile
Name of the formatted file to be printed
logical, intent(in), optional :: save_data
If .TRUE., saves the read data into the TYPE member variables
Calls
Called by
Contents
Variables
abs_pos exist final_save_data finalnamefile itr max_npart min_abs_y min_abs_z1 min_abs_z2 min_y_index
Variables
Type Visibility Attributes Name Initial
double precision, private, DIMENSION(:, :), ALLOCATABLE :: abs_pos
logical, private :: exist
logical, private :: final_save_data
character(len=:), private, ALLOCATABLE :: finalnamefile
integer, private :: itr
integer, private, parameter :: max_npart = 2.D+7
double precision, private :: min_abs_y
double precision, private :: min_abs_z1
double precision, private :: min_abs_z2
integer, private :: min_y_index
Call graph
read_sphincs_dump_print_formatted calls u, divv, h, read_sphincs_dump, ye, nlrf, theta, av, deallocate_sph_memory, alive, allocate_sph_memory, set_units, pr, pos_u, vel_u, temp, nu, read_sphincs_dump_print_formatted