reflect_particles_xy_plane – SPHINCS_ID
reflect_particles_xy_plane Module Procedure
24 statements
Source File
module procedure reflect_particles_xy_plane module module subroutine reflect_particles_xy_plane(npart, pos, pos_below, npart_above_xy, above_xy_plane_a, nu, nu_below) Interface →
Reflect the particle with z>0 with respect to the xy plane
FT 25.03.2022
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npart
double precision, intent(inout), DIMENSION(3,npart) :: pos
double precision, intent(out), DIMENSION(3,npart_above_xy) :: pos_below
integer, intent(inout) :: npart_above_xy
integer, intent(in), DIMENSION(npart_above_xy) :: above_xy_plane_a
double precision, intent(inout), optional DIMENSION(npart) :: nu
double precision, intent(out), optional DIMENSION(npart_above_xy) :: nu_below
Called by
Contents
Variables
a nu_tmp pos_tmp
Variables
Type Visibility Attributes Name Initial
integer, private :: a
double precision, private, DIMENSION(npart) :: nu_tmp
double precision, private, DIMENSION(3,npart) :: pos_tmp
Call graph
reflect_particles_xy_plane calls reflect_particles_xy_plane
impose_equatorial_plane_symmetry calls reflect_particles_xy_plane, impose_equatorial_plane_symmetry
construct_particles_std calls impose_equatorial_plane_symmetry, construct_particles_std
perform_apm calls impose_equatorial_plane_symmetry, perform_apm
particles calls construct_particles_std
convergence_test calls particles
sphincs_id calls particles