run_kadath_reader – SPHINCS_ID
run_kadath_reader Module Procedure
217 statements
Source File
module procedure run_kadath_reader module module subroutine run_kadath_reader(this, mpi_ranks, nx, ny, nz, xmin, xmax, ymin, ymax, zmin, zmax, coords, lapse, shift_x, shift_y, shift_z, g_xx, g_xy, g_xz, g_yy, g_yz, g_zz, k_xx, k_xy, k_xz, k_yy, k_yz, k_zz, mass_density, specific_energy, pressure, v_eul_x, v_eul_y, v_eul_z, filename) Interface →
Uses
IFPORT
utility
Calls the MPI-parallelized version of the function KadathExportBNS within Kadath
Created: FT 28.06.2022 Last update: FT 28.06.2022
Arguments
Type Intent Optional Attributes Name
class(bnsfuka), intent(inout) :: this
bnsfuka object which this PROCEDURE is a member of
integer, intent(in) :: mpi_ranks
Number of MPI ranks
integer, intent(in) :: nx
Number of lattice points in the direction
integer, intent(in) :: ny
Number of lattice points in the direction
integer, intent(in) :: nz
Number of lattice points in the direction
double precision, intent(in) :: xmin
Minimum value for over the lattice
double precision, intent(in) :: xmax
Maximum value for over the lattice
double precision, intent(in) :: ymin
Minimum value for over the lattice
double precision, intent(in) :: ymax
Maximum value for over the lattice
double precision, intent(in) :: zmin
Minimum value for over the lattice
double precision, intent(in) :: zmax
Maximum value for over the lattice
double precision, intent(inout), DIMENSION(nx,ny,nz,3) :: coords
Array containing the \(\mathrm{ID}\) on a lattice. First three indices run over the lattice's dimensions, the fourth one runs ovr the fields
double precision, intent(inout), DIMENSION(nx,ny,nz) :: lapse
double precision, intent(inout), DIMENSION(nx,ny,nz) :: shift_x
double precision, intent(inout), DIMENSION(nx,ny,nz) :: shift_y
double precision, intent(inout), DIMENSION(nx,ny,nz) :: shift_z
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_xx
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_xy
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_xz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_yy
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_yz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: g_zz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_xx
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_xy
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_xz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_yy
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_yz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: k_zz
double precision, intent(inout), DIMENSION(nx,ny,nz) :: mass_density
double precision, intent(inout), DIMENSION(nx,ny,nz) :: specific_energy
double precision, intent(inout), DIMENSION(nx,ny,nz) :: pressure
double precision, intent(inout), DIMENSION(nx,ny,nz) :: v_eul_x
double precision, intent(inout), DIMENSION(nx,ny,nz) :: v_eul_y
double precision, intent(inout), DIMENSION(nx,ny,nz) :: v_eul_z
character(len=*), intent(in) :: filename
Path to the \(\mathrm{ID}\) file output by \(\texttt{FUKA}\), as given in the parameter fe sphincs_id_parameters.dat
Calls
Called by
Contents
Variables
debug dir_id dir_out exist filename_id filename_par filename_rank grid_tmp i i_char i_field i_file i_rank ios j k mpi_ranks_str n_first_ranks n_last_rank nlines npoints_prev nz_prev nz_rank nz_rem size_run_id_str status unit_par unit_rank unit_rank_prev work_dir
Variables
Type Visibility Attributes Name Initial
logical, private, parameter :: debug = .FALSE.
character(len=:), private, ALLOCATABLE :: dir_id
logical, private :: dir_out
logical, private :: exist
character(len=:), private, ALLOCATABLE :: filename_id
character(len=:), private, ALLOCATABLE :: filename_par
character(len=:), private, ALLOCATABLE :: filename_rank
double precision, private, DIMENSION(:,:), ALLOCATABLE :: grid_tmp
integer, private :: i
integer, private :: i_char
integer, private :: i_field
integer, private :: i_file
integer, private :: i_rank
integer, private :: ios
integer, private :: j
integer, private :: k
character(len=3), private :: mpi_ranks_str
integer, private :: n_first_ranks
integer, private :: n_last_rank
integer, private :: nlines
integer, private :: npoints_prev
integer, private :: nz_prev
integer, private :: nz_rank(mpi_ranks)
integer, private :: nz_rem
character(len=3), private :: size_run_id_str
logical(kind=4), private :: status
integer, private, parameter :: unit_par = 3480
integer, private, DIMENSION(mpi_ranks) :: unit_rank
integer, private :: unit_rank_prev
character(len=:), private, ALLOCATABLE :: work_dir
Call graph
run_kadath_reader calls stringize, changedirqq, makedirqq, run_kadath_reader