setup_standard_tpo_variables – SPHINCS_ID
setup_standard_tpo_variables Module Procedure
147 statements
Source File
module procedure setup_standard_tpo_variables module module subroutine setup_standard_tpo_variables(ftpo, id, dx, dy, dz) Interface →
Uses
tensor
utility
bns_fuka
mesh_refinement
Read the gravity grid parameters, computes * gravity grid coordinates, imports the * spacetime ID on the gravity grid, and * performs some checks on it. * Its input includes the numbers of grid points * per axis, contrary to * construct_formul_tpo_bns_grid * where those numbers are replaced by the grid * spacings. * * FT 22.10.2020 * Last updated: FT 05.07.2022 * *
Arguments
Type Intent Optional Attributes Name
class(tpo), intent(inout) :: ftpo
class(idbase), intent(inout) :: id
double precision, optional :: dx
double precision, optional :: dy
double precision, optional :: dz
Calls
Called by
Contents
Variables
detg i i_matter j k l sizes system_size
Variables
Type Visibility Attributes Name Initial
double precision, private :: detg
integer, private :: i
integer, private :: i_matter
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private, DIMENSION(id% get_n_matter(),6) :: sizes
double precision, private, DIMENSION(6) :: system_size
Call graph
setup_standard_tpo_variables calls levels, allocate_grid_function, timer, deallocate_grid_function, initialize_grid, determinant_sym3x3, setup_standard_tpo_variables