setup_standard3p1_variables – SPHINCS_LORENE
setup_standard3p1_variables Module Procedure
GNU Free Documentation License
94 statements
Source File
module procedure setup_standard3p1_variables module module subroutine setup_standard3p1_variables(f3p1, id, dx, dy, dz) Interface →
Uses
tensor
mesh_refinement
utility
Read the gravity grid parameters, computes * gravity grid coordinates, imports the LORENE * spacetime ID on the gravity grid, and * performs some checks on it. * Its input includes the numbers of grid points * per axis, contrary to * construct_formul_3p1_bns_grid * where those numbers are replaced by the grid * spacings. * * FT 22.10.2020 * *
Arguments
Type Intent Optional Attributes Name
class(formul_3p1), intent(inout) :: f3p1
class(idbase), intent(inout) :: id
double precision, optional :: dx
double precision, optional :: dy
double precision, optional :: dz
Calls
Called by
Contents
Variables
detg i j k l system_size
Variables
Type Visibility Attributes Name Initial
double precision, private :: detg
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: l
double precision, private, DIMENSION(6) :: system_size
Call graph
setup_standard3p1_variables calls allocate_grid_function, deallocate_grid_function, levels, timer, initialize_grid, determinant_sym3x3_grid, setup_standard3p1_variables