shorten_eos_name – SPHINCS_ID
shorten_eos_name Function
46 statements
Source File
public function shorten_eos_name(eos_long) result(eos_str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: eos_long
Return Value character(len=4)
Called by
Contents
Source Code
shorten_eos_name
Source Code
  FUNCTION shorten_eos_name( eos_long ) RESULT( eos_str )
    !*********************************************
    !                                            *
    ! Converts the longer names from LORENE      *
    ! to the 4-character strings needed by       *
    ! select_EOS_parameters                      *
    !                                            *
    ! FT 11.08.2021                              *
    !                                            *
    !*********************************************
    IMPLICIT NONE
    CHARACTER(4):: eos_str
    CHARACTER( LEN=* ), INTENT(IN):: eos_long
    SELECT CASE( eos_long )
      CASE( 'Multipolytropic SLy  EOS' )
        eos_str= 'SLy '
      CASE( 'Multipolytropic ALF2 EOS' )
        eos_str= 'ALF2'
      CASE( 'Multipolytropic ALF4 EOS' )
        eos_str= 'ALF4'
      CASE( 'Multipolytropic ENG  EOS' )
        eos_str= 'ENG '
      CASE( 'Multipolytropic H4  EOS' )
        eos_str= 'H4  '
      CASE( 'Multipolytropic MPA1 EOS' )
        eos_str= 'MPA1'
      CASE( 'Star 1  Multipolytropic MPA1 EOS' )
        eos_str= 'MPA1'
      CASE( 'Multipolytropic MS1  EOS' )
        eos_str= 'MS1 '
      CASE( 'Multipolytropic MS1b EOS' )
        eos_str= 'MS1b'
      CASE( 'Multipolytropic APR3 EOS' )
        eos_str= 'AP3 '
      CASE( 'Multipolytropic AP3  EOS' )
        eos_str= 'AP3 '
      CASE( 'Multipolytropic WFF1 EOS' )
        eos_str= 'WFF1'
      CASE( 'Multipolytropic WFF2 EOS' )
        eos_str= 'WFF2'
      CASE( 'Multipolytropic GNH3 EOS' )
        eos_str= 'GNH3'
      CASE( 'Multipolytropic APR4 EOS' )
        eos_str= 'APR4'
      CASE( 'Multipolytropic AP4  EOS' )
        eos_str= 'APR4'
      CASE( 'Multipolytropic haso EOS' )
        eos_str= 'haso'
      CASE DEFAULT
        PRINT *, "** ERROR! Unknown EOS name: ", eos_long
        PRINT *, " * Please add the name to SUBROUTINE shorten_eos_name. ", &
                 "   This SUBROUTINE exists mostly for backward compatibility."
        PRINT *, " * Stopping..."
        STOP
    END SELECT
  END FUNCTION shorten_eos_name
Call graph
import_id_params calls shorten_eos_name, import_id_params
import_diffstar_params calls shorten_eos_name, import_diffstar_params
construct_diffstarlorene calls import_diffstar_params, construct_diffstarlorene
construct_bnslorene calls import_id_params, construct_bnslorene