spherical_from_cartesian – SPHINCS_ID
spherical_from_cartesian Subroutine
26 statements
Source File
public pure subroutine spherical_from_cartesian(x, y, z, xo, yo, zo, r, theta, phi)
Uses
constants
Compute the spherical polar coordinates of a point relative to a point , starting from the Cartesian coordinates of the points and
FT 14.01.2021
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: x
coordinate of the point
double precision, intent(in) :: y
coordinate of the point
double precision, intent(in) :: z
coordinate of the point
double precision, intent(in) :: xo
coordinate of the point
double precision, intent(in) :: yo
coordinate of the point
double precision, intent(in) :: zo
coordinate of the point
double precision, intent(out) :: r
coordinate of the point , relative to
double precision, intent(out) :: theta
coordinate (colatitude) of the point , relative to
double precision, intent(out) :: phi
coordinate (azimuth) of the point , relative to
Called by
Contents
Variables
xd yd zd
Source Code
spherical_from_cartesian
Variables
Type Visibility Attributes Name Initial
double precision, public :: xd
double precision, public :: yd
double precision, public :: zd
Source Code
  PURE SUBROUTINE spherical_from_cartesian( x, y, z, xo, yo, zo, r, theta, phi )
    !****************************************************************
    !
    !# Compute the spherical polar coordinates of a point \(p\)
    !  relative to a point \(O\), starting from the Cartesian
    !  coordinates of the points \(p\) and \(O\)
    !
    !  FT 14.01.2021
    !
    !****************************************************************
    USE constants, ONLY: pi
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN):: x
    !! \(x\) coordinate of the point \(p\)
    DOUBLE PRECISION, INTENT(IN):: y
    !! \(y\) coordinate of the point \(p\)
    DOUBLE PRECISION, INTENT(IN):: z
    !! \(z\) coordinate of the point \(p\)
    DOUBLE PRECISION, INTENT(IN):: xo
    !! \(x\) coordinate of the point \(O\)
    DOUBLE PRECISION, INTENT(IN):: yo
    !! \(y\) coordinate of the point \(O\)
    DOUBLE PRECISION, INTENT(IN):: zo
    !! \(z\) coordinate of the point \(O\)
    DOUBLE PRECISION, INTENT(OUT):: r
    !! \(r\) coordinate of the point \(p\), relative to \(O\)
    DOUBLE PRECISION, INTENT(OUT):: theta
    !! \(\theta\) coordinate (colatitude) of the point \(p\), relative to \(O\)
    DOUBLE PRECISION, INTENT(OUT):: phi
    !! \(\phi\) coordinate (azimuth) of the point \(p\), relative to \(O\)
    DOUBLE PRECISION:: xd, yd, zd
    xd= x - xo
    yd= y - yo
    zd= z - zo
    IF( x > zero )THEN
      phi= ATAN( yd/xd )
    ELSEIF( x < zero )THEN
      phi= ATAN( yd/xd ) + pi
    ELSE
      phi= pi/2.D0
    ENDIF
    r= SQRT( xd**2.D0 + yd**2.D0 + zd**2.D0 )
    theta= ACOS( zd/r )
  END SUBROUTINE spherical_from_cartesian
Call graph
perform_apm calls spherical_from_cartesian, place_and_print_ghost_particles, perform_apm
construct_particles_std calls spherical_from_cartesian, construct_particles_std
interpolate_mass_density calls spherical_from_cartesian, interpolate_mass_density
particles calls construct_particles_std
convergence_test calls particles
sphincs_id calls particles