test_recovery_m2p – SPHINCS_ID
test_recovery_m2p Module Procedure
175 statements
Source File
module procedure test_recovery_m2p module module subroutine test_recovery_m2p(this, parts, namefile) Interface →
Uses
deactivate_particles
input_output
units
gradient
metric_on_particles
utility
recovery
mesh_refinement
tensor
McLachlan_refine
ADM_refine
BSSN_refine
alive_flag
sph_variables
constants
Tests the recovery using the metric mapped from the emsh to the particles. Computes the conserved variables from the physical ones, and then the physical ones from the conserved ones. It then compares the variables computed with the recovery PROCEDURES, with those computed with \(\texttt{SPHINCS_ID}\).
Todo
add reference for recovery
FT 25.02.2020
Arguments
Type Intent Optional Attributes Name
class(tpo), intent(in) :: this
tpo object which this PROCEDURE is a member of
class(particles), intent(in) :: parts
particles object used to map the metric from the mesh to the particles, and to call the recovery procedures
character(len=*), intent(inout) :: namefile
Name of the formatted file where the data is printed
Calls
Called by
Contents
Variables
a debug e_hat_rec exist finalnamefile i_mat i_matter l nlrf_rec npart nstar nstar_rec pos pr_rec s_l_rec theta_rec u_rec unit_recovery vel_u_rec
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, parameter :: debug = .FALSE.
double precision, private, DIMENSION(:), ALLOCATABLE :: e_hat_rec
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
character(len=2), private :: i_mat
integer, private :: i_matter
integer, private :: l
double precision, private, DIMENSION(:), ALLOCATABLE :: nlrf_rec
integer, private :: npart
double precision, private, DIMENSION(:), ALLOCATABLE :: nstar
double precision, private, DIMENSION(:), ALLOCATABLE :: nstar_rec
double precision, private, DIMENSION(:,:), ALLOCATABLE :: pos
double precision, private, DIMENSION(:), ALLOCATABLE :: pr_rec
double precision, private, DIMENSION(:,:), ALLOCATABLE :: s_l_rec
double precision, private, DIMENSION(:), ALLOCATABLE :: theta_rec
double precision, private, DIMENSION(:), ALLOCATABLE :: u_rec
integer, private, parameter :: unit_recovery = 34156
double precision, private, DIMENSION(:,:), ALLOCATABLE :: vel_u_rec
Call graph
test_recovery_m2p calls set_units, nlrf_fb, get_metric_on_particles, u_fb, read_options, allocate_grid_function, cs_fb, allocate_metric_on_particles, vel_u_fb, deallocate_ztmp, cons_2_phys, levels, deallocate_adm, allocate_gradient, deallocate_bssn, allocate_bssn, theta_fb, allocate_sph_memory, deallocate_grid_function, allocate_ztmp, phys_2_cons, deallocate_sph_memory, alive, pr_fb, allocate_adm, deallocate_metric_on_particles, deallocate_gradient, test_recovery_m2p