test_recovery – SPHINCS_ID
test_recovery Module Procedure
126 statements
Source File
module procedure test_recovery module module subroutine test_recovery(this, npart, pos, nlrf, u, pr, vel_u, theta, nstar) Interface →
Uses
deactivate_particles
metric_on_particles
utility
recovery
tensor
constants
Tests the recovery. Computes the conserved variables from the physical ones, and then the physical ones from the conserved ones. It then compares the variables computed with the recovery PROCEDURES, with those computed with \(\texttt{SPHINCS_ID}\).
Todo
add reference for recovery
FT 18.02.2022
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: this
particles object which this PROCEDURE is a member of
integer, intent(in) :: npart
Particle number
double precision, intent(in), DIMENSION(3,npart) :: pos
Particle positions
double precision, intent(in), DIMENSION(npart) :: nlrf
Baryon density in the local rest frame on the particles
double precision, intent(in), DIMENSION(npart) :: u
Specific internal energy on the particles
double precision, intent(in), DIMENSION(npart) :: pr
Pressure on the particles
double precision, intent(in), DIMENSION(3,npart) :: vel_u
Spatial velocity in the computing frame on the particles
double precision, intent(in), DIMENSION(npart) :: theta
Generalized Lorentz factor on the particles
double precision, intent(in), DIMENSION(npart) :: nstar
Proper baryon density in the local rest frame on the particles
Canonical momentum on the particles
Canonical energy on the particles
Name of the formatted file where the data is printed
Calls
Called by
Contents
Variables
a debug det e_hat_rec exist finalnamefile i_mat i_matter nlrf_rec nstar_rec pr_rec s_l_rec theta_rec u_rec unit_recovery vel_u_rec
Variables
Type Visibility Attributes Name Initial
integer, private :: a
logical, private, parameter :: debug = .FALSE.
double precision, private :: det
double precision, private, DIMENSION(npart) :: e_hat_rec
logical, private :: exist
character(len=:), private, ALLOCATABLE :: finalnamefile
character(len=2), private :: i_mat
integer, private :: i_matter
double precision, private, DIMENSION(npart) :: nlrf_rec
double precision, private, DIMENSION(npart) :: nstar_rec
double precision, private, DIMENSION(npart) :: pr_rec
double precision, private, DIMENSION(3,npart) :: s_l_rec
double precision, private, DIMENSION(npart) :: theta_rec
double precision, private, DIMENSION(npart) :: u_rec
integer, private, parameter :: unit_recovery = 34956
double precision, private, DIMENSION(3,npart) :: vel_u_rec
Call graph
test_recovery calls pr_fb, nlrf_fb, deallocate_metric_on_particles, cs_fb, theta_fb, u_fb, determinant_sym4x4, allocate_metric_on_particles, vel_u_fb, phys_2_cons, compute_g4, cons_2_phys, g4_ll, test_recovery