allocate_lorene_id_parts_memory – SPHINCS_LORENE
allocate_lorene_id_parts_memory Interface
GNU Free Documentation License
100 statements
Source File
interface
Calls
Called by
public module module subroutine allocate_lorene_id_parts_memory(THIS) Implementation →
Arguments
Type Intent Optional Attributes Name
class(particles), intent(inout) :: THIS
particles object which this PROCEDURE is a member of
Description
Allocates allocatable arrays member of a particles object
Call graph
allocate_lorene_id_parts_memory calls allocate_lorene_id_parts_memory
construct_particles calls allocate_lorene_id_parts_memory, construct_particles
particles calls construct_particles
convergence_test calls particles
sphincs_lorene_bns calls particles