bnslorene – SPHINCS_LORENE
bnslorene Interface
GNU Free Documentation License
3 statements
Source File
public interface bnslorene
Interface of TYPE bnslorene
Calls
Called by
Contents
Module Procedures
construct_bnslorene
Module Procedures
public interface construct_bnslorene()
Arguments
None
Call graph
bnslorene calls construct_bnslorene
construct_bnslorene calls construct_bnslorene, timer, import_id_params
import_id_params calls import_id_params, print_id_params, get_lorene_id_params, k_lorene2hydrobase_piecewisepolytrope, k_lorene2hydrobase
print_id_params calls print_id_params, k_lorene2hydrobase
convergence_test calls bnslorene