bssn_constraint_terms_interior – SPHINCS_ID
bssn_constraint_terms_interior Interface
55 statements
Source File
interface
Called by
public subroutine bssn_constraint_terms_interior(nx, ny, nz, imin, imax, dx, dy, dz, gt11, gt12, gt13, gt22, gt23, gt33, At11, At12, At13, At22, At23, At33, trk, phi, Xt1, Xt2, Xt3, eTtt, eTtx, eTty, eTtz, eTxx, eTxy, eTxz, eTyy, eTyz, eTzz, alp, beta1, beta2, beta3, cXt1, cXt2, cXt3, Ham, M1, M2, M3, rho, s1, s2, s3) bind(C, NAME="0")
Arguments
Type Intent Optional Attributes Name
integer(kind=C_INT), intent(in), VALUE :: nx
integer(kind=C_INT), intent(in), VALUE :: ny
integer(kind=C_INT), intent(in), VALUE :: nz
integer(kind=C_INT), intent(in), DIMENSION(3) :: imin
integer(kind=C_INT), intent(in), DIMENSION(3) :: imax
real(kind=C_DOUBLE), intent(in), VALUE :: dx
real(kind=C_DOUBLE), intent(in), VALUE :: dy
real(kind=C_DOUBLE), intent(in), VALUE :: dz
real(kind=C_DOUBLE), intent(in) :: gt11(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: gt12(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: gt13(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: gt22(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: gt23(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: gt33(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At11(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At12(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At13(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At22(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At23(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: At33(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: trk(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: phi(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: Xt1(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: Xt2(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: Xt3(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTtt(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTtx(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTty(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTtz(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTxx(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTxy(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTxz(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTyy(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTyz(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: eTzz(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: alp(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: beta1(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: beta2(nx,ny,nz)
real(kind=C_DOUBLE), intent(in) :: beta3(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: cXt1(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: cXt2(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: cXt3(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: Ham(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: M1(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: M2(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: M3(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: rho(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: s1(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: s2(nx,ny,nz)
real(kind=C_DOUBLE), intent(out) :: s3(nx,ny,nz)
Description
ML_BSSN_NV_ConstraintTermsInterior_Body
FT 03.02.2022
Call graph
compute_and_export_bssn_constraints_particles calls bssn_constraint_terms_interior, compute_and_export_bssn_constraints_particles
compute_and_export_bssn_constraints_grid calls bssn_constraint_terms_interior, compute_and_export_bssn_constraints_grid