compute_adm_momentum_fluid – SPHINCS_ID
compute_adm_momentum_fluid Interface
4 statements
Source File
public interface compute_adm_momentum_fluid
Computes an estimate of the linear momentum of the fluid
Calls
Contents
Module Procedures
compute_adm_momentum_fluid_fields compute_adm_momentum_fluid_canmom
Module Procedures
public interface compute_adm_momentum_fluid_fields()
Arguments
None
public interface compute_adm_momentum_fluid_canmom()
Arguments
None
Call graph
compute_adm_momentum_fluid calls compute_adm_momentum_fluid_canmom, compute_adm_momentum_fluid_fields
compute_adm_momentum_fluid_canmom calls compute_adm_momentum_fluid_canmom, spatial_vector_norm_sym3x3
compute_adm_momentum_fluid_fields calls compute_adm_momentum_fluid_fields, determinant_sym4x4, compute_g4, spatial_vector_norm_sym3x3, lower_index_4vector