diffstarlorene – SPHINCS_LORENE
diffstarlorene Interface
GNU Free Documentation License
3 statements
Source File
public interface diffstarlorene
Interface of TYPE diffstarlorene
Calls
Called by
Contents
Module Procedures
construct_diffstarlorene
Module Procedures
public interface construct_diffstarlorene()
Arguments
None
Call graph
diffstarlorene calls construct_diffstarlorene
construct_diffstarlorene calls construct_diffstarlorene, import_diffstar_params, timer
import_diffstar_params calls import_diffstar_params, get_diffstar_params, k_lorene2hydrobase_piecewisepolytrope, print_diffstar_params, k_lorene2hydrobase
print_diffstar_params calls print_diffstar_params, k_lorene2hydrobase
sphincs_lorene_bns calls diffstarlorene