get_lorene_id_params – SPHINCS_ID
get_lorene_id_params Interface
232 statements
Source File
interface
Called by
private subroutine get_lorene_id_params(optr, angular_vel, distance, distance_com, mass1, mass2, mass_grav1, mass_grav2, adm_mass, linear_momentum_x, linear_momentum_y, linear_momentum_z, angular_momentum_x, angular_momentum_y, angular_momentum_z, area_radius1, radius1_x_comp, radius1_y, radius1_z, radius1_x_opp, center1_x, barycenter1_x, area_radius2, radius2_x_comp, radius2_y, radius2_z, radius2_x_opp, center2_x, barycenter2_x, ent_center1, nbar_center1, rho_center1, energy_density_center1, specific_energy_center1, pressure_center1, ent_center2, nbar_center2, rho_center2, energy_density_center2, specific_energy_center2, pressure_center2, eos1, eos2, eos1_id, eos2_id, gamma_1, kappa_1, gamma_2, kappa_2, npeos_1, gamma0_1, gamma1_1, gamma2_1, gamma3_1, kappa0_1, kappa1_1, kappa2_1, kappa3_1, logP1_1, logRho0_1, logRho1_1, logRho2_1, npeos_2, gamma0_2, gamma1_2, gamma2_2, gamma3_2, kappa0_2, kappa1_2, kappa2_2, kappa3_2, logP1_2, logRho0_2, logRho1_2, logRho2_2) bind(C, NAME= "0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), intent(in), VALUE :: optr
C pointer pointing to a \(\texttt{LORENE}\) \(\texttt{Bin_NS}\) object
real(kind=C_DOUBLE), intent(out) :: angular_vel
real(kind=C_DOUBLE), intent(out) :: distance
real(kind=C_DOUBLE), intent(out) :: distance_com
real(kind=C_DOUBLE), intent(out) :: mass1
real(kind=C_DOUBLE), intent(out) :: mass2
real(kind=C_DOUBLE), intent(out) :: mass_grav1
real(kind=C_DOUBLE), intent(out) :: mass_grav2
real(kind=C_DOUBLE), intent(out) :: adm_mass
real(kind=C_DOUBLE), intent(out) :: linear_momentum_x
real(kind=C_DOUBLE), intent(out) :: linear_momentum_y
real(kind=C_DOUBLE), intent(out) :: linear_momentum_z
real(kind=C_DOUBLE), intent(out) :: angular_momentum_x
real(kind=C_DOUBLE), intent(out) :: angular_momentum_y
real(kind=C_DOUBLE), intent(out) :: angular_momentum_z
real(kind=C_DOUBLE), intent(out) :: area_radius1
real(kind=C_DOUBLE), intent(out) :: radius1_x_comp
real(kind=C_DOUBLE), intent(out) :: radius1_y
real(kind=C_DOUBLE), intent(out) :: radius1_z
real(kind=C_DOUBLE), intent(out) :: radius1_x_opp
real(kind=C_DOUBLE), intent(out) :: center1_x
real(kind=C_DOUBLE), intent(out) :: barycenter1_x
real(kind=C_DOUBLE), intent(out) :: area_radius2
real(kind=C_DOUBLE), intent(out) :: radius2_x_comp
real(kind=C_DOUBLE), intent(out) :: radius2_y
real(kind=C_DOUBLE), intent(out) :: radius2_z
real(kind=C_DOUBLE), intent(out) :: radius2_x_opp
real(kind=C_DOUBLE), intent(out) :: center2_x
real(kind=C_DOUBLE), intent(out) :: barycenter2_x
real(kind=C_DOUBLE), intent(out) :: ent_center1
real(kind=C_DOUBLE), intent(out) :: nbar_center1
real(kind=C_DOUBLE), intent(out) :: rho_center1
real(kind=C_DOUBLE), intent(out) :: energy_density_center1
real(kind=C_DOUBLE), intent(out) :: specific_energy_center1
real(kind=C_DOUBLE), intent(out) :: pressure_center1
real(kind=C_DOUBLE), intent(out) :: ent_center2
real(kind=C_DOUBLE), intent(out) :: nbar_center2
real(kind=C_DOUBLE), intent(out) :: rho_center2
real(kind=C_DOUBLE), intent(out) :: energy_density_center2
real(kind=C_DOUBLE), intent(out) :: specific_energy_center2
real(kind=C_DOUBLE), intent(out) :: pressure_center2
character(kind=C_CHAR), intent(out), DIMENSION(100) :: eos1
character(kind=C_CHAR), intent(out), DIMENSION(100) :: eos2
integer(kind=C_INT) :: eos1_id
integer(kind=C_INT) :: eos2_id
real(kind=C_DOUBLE), intent(out) :: gamma_1
real(kind=C_DOUBLE), intent(out) :: kappa_1
real(kind=C_DOUBLE), intent(out) :: gamma_2
real(kind=C_DOUBLE), intent(out) :: kappa_2
integer(kind=C_INT) :: npeos_1
real(kind=C_DOUBLE), intent(out) :: gamma0_1
real(kind=C_DOUBLE), intent(out) :: gamma1_1
real(kind=C_DOUBLE), intent(out) :: gamma2_1
real(kind=C_DOUBLE), intent(out) :: gamma3_1
real(kind=C_DOUBLE), intent(out) :: kappa0_1
real(kind=C_DOUBLE), intent(out) :: kappa1_1
real(kind=C_DOUBLE), intent(out) :: kappa2_1
real(kind=C_DOUBLE), intent(out) :: kappa3_1
real(kind=C_DOUBLE), intent(out) :: logP1_1
real(kind=C_DOUBLE), intent(out) :: logRho0_1
real(kind=C_DOUBLE), intent(out) :: logRho1_1
real(kind=C_DOUBLE), intent(out) :: logRho2_1
integer(kind=C_INT) :: npeos_2
real(kind=C_DOUBLE), intent(out) :: gamma0_2
real(kind=C_DOUBLE), intent(out) :: gamma1_2
real(kind=C_DOUBLE), intent(out) :: gamma2_2
real(kind=C_DOUBLE), intent(out) :: gamma3_2
real(kind=C_DOUBLE), intent(out) :: kappa0_2
real(kind=C_DOUBLE), intent(out) :: kappa1_2
real(kind=C_DOUBLE), intent(out) :: kappa2_2
real(kind=C_DOUBLE), intent(out) :: kappa3_2
real(kind=C_DOUBLE), intent(out) :: logP1_2
real(kind=C_DOUBLE), intent(out) :: logRho0_2
real(kind=C_DOUBLE), intent(out) :: logRho1_2
real(kind=C_DOUBLE), intent(out) :: logRho2_2
Description
Interface to the \(\texttt{LORENE}\) method of class \(\texttt{Bin_NS}\) with the same name, that stores the physical parameters of the binary system from \(\texttt{LORENE}\) in the desired variables
FT
Call graph
import_id_params calls get_lorene_id_params, import_id_params
construct_bnslorene calls import_id_params, construct_bnslorene