get_diffstar_full – SPHINCS_ID
get_diffstar_full Interface
GNU Free Documentation License
182 statements
Source File
interface
Called by
private subroutine get_diffstar_full(optr, x, y, z, lapse, shift_x, shift_y, shift_z, g_diag, k_xx, k_xy, k_xz, k_yy, k_yz, k_zz, baryon_density, energy_density, specific_energy, v_euler_x, v_euler_y, v_euler_z) bind(C, NAME= "0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), intent(in), VALUE :: optr
C pointer pointing to a \(\texttt{LORENE}\) \(\texttt{Et_diffrot}\) object
real(kind=C_DOUBLE), intent(in), VALUE :: x
coordinate of the desired point
real(kind=C_DOUBLE), intent(in), VALUE :: y
coordinate of the desired point
real(kind=C_DOUBLE), intent(in), VALUE :: z
coordinate of the desired point
real(kind=C_DOUBLE), intent(out) :: lapse
real(kind=C_DOUBLE), intent(out) :: shift_x
real(kind=C_DOUBLE), intent(out) :: shift_y
real(kind=C_DOUBLE), intent(out) :: shift_z
real(kind=C_DOUBLE), intent(out) :: g_diag
real(kind=C_DOUBLE), intent(out) :: k_xx
real(kind=C_DOUBLE), intent(out) :: k_xy
real(kind=C_DOUBLE), intent(out) :: k_xz
real(kind=C_DOUBLE), intent(out) :: k_yy
real(kind=C_DOUBLE), intent(out) :: k_yz
real(kind=C_DOUBLE), intent(out) :: k_zz
real(kind=C_DOUBLE), intent(out) :: baryon_density
real(kind=C_DOUBLE), intent(out) :: energy_density
real(kind=C_DOUBLE), intent(out) :: specific_energy
real(kind=C_DOUBLE), intent(out) :: v_euler_x
real(kind=C_DOUBLE), intent(out) :: v_euler_y
real(kind=C_DOUBLE), intent(out) :: v_euler_z
Description
Interface to the \(\texttt{LORENE}\) method of class \(\texttt{Et_diffrot}\) with the same name, that reads the full \(\texttt{LORENE}\) ID at the specified point. That is, imports the metric fields, the components of the extrinsic curvature [c/km], and the hydro fields.
shift vector [c]
baryon mass density [kg m^{-3}]
energy density [kg c^2 m^{-3}]
pressure [kg c^2 m^{-3}]
specific internal energy [c^2]
fluid 3-velocity with respect to the Eulerian observer [c]
FT 24.10.2021
Call graph
import_id_int calls get_diffstar_full, import_id_int
import_id_full calls get_diffstar_full, import_id_full