get_diffstar_params – SPHINCS_LORENE
get_diffstar_params Interface
GNU Free Documentation License
182 statements
Source File
interface
Called by
private subroutine get_diffstar_params(optr, omega_c, mass, mass_grav, angular_momentum, tsw, grv2, grv3, r_circ, surface_area, r_mean, r_eq, r_eq_pi2, r_eq_pi, r_eq_3pi2, r_eq_pole, r_ratio, r_isco, f_isco, specific_energy_isco, specific_angular_momentum_isco, area_radius, ent_center, nbar_center, rho_center, energy_density_center, specific_energy_center, pressure_center, redshift_eqf, redshift_eqb, redshift_pole, eos, eos_id, gamma, kappa, npeos, gamma0, gamma1, gamma2, gamma3, kappa0, kappa1, kappa2, kappa3, logP1, logRho0, logRho1, logRho2) bind(C, NAME= "0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), intent(in), VALUE :: optr
C pointer pointing to a \(\texttt{LORENE}\) \(\texttt{Et_diffrot}\) object
real(kind=C_DOUBLE), intent(out) :: omega_c
real(kind=C_DOUBLE), intent(out) :: mass
real(kind=C_DOUBLE), intent(out) :: mass_grav
real(kind=C_DOUBLE), intent(out) :: angular_momentum
real(kind=C_DOUBLE), intent(out) :: tsw
real(kind=C_DOUBLE), intent(out) :: grv2
real(kind=C_DOUBLE), intent(out) :: grv3
real(kind=C_DOUBLE), intent(out) :: r_circ
real(kind=C_DOUBLE), intent(out) :: surface_area
real(kind=C_DOUBLE), intent(out) :: r_mean
real(kind=C_DOUBLE), intent(out) :: r_eq
real(kind=C_DOUBLE), intent(out) :: r_eq_pi2
real(kind=C_DOUBLE), intent(out) :: r_eq_pi
real(kind=C_DOUBLE), intent(out) :: r_eq_3pi2
real(kind=C_DOUBLE), intent(out) :: r_eq_pole
real(kind=C_DOUBLE), intent(out) :: r_ratio
real(kind=C_DOUBLE), intent(out) :: r_isco
real(kind=C_DOUBLE), intent(out) :: f_isco
real(kind=C_DOUBLE), intent(out) :: specific_energy_isco
real(kind=C_DOUBLE), intent(out) :: specific_angular_momentum_isco
real(kind=C_DOUBLE), intent(out) :: area_radius
real(kind=C_DOUBLE), intent(out) :: ent_center
real(kind=C_DOUBLE), intent(out) :: nbar_center
real(kind=C_DOUBLE), intent(out) :: rho_center
real(kind=C_DOUBLE), intent(out) :: energy_density_center
real(kind=C_DOUBLE), intent(out) :: specific_energy_center
real(kind=C_DOUBLE), intent(out) :: pressure_center
real(kind=C_DOUBLE), intent(out) :: redshift_eqf
real(kind=C_DOUBLE), intent(out) :: redshift_eqb
real(kind=C_DOUBLE), intent(out) :: redshift_pole
character(kind=C_CHAR), intent(out), DIMENSION(100) :: eos
integer(kind=C_INT) :: eos_id
real(kind=C_DOUBLE), intent(out) :: gamma
real(kind=C_DOUBLE), intent(out) :: kappa
integer(kind=C_INT) :: npeos
real(kind=C_DOUBLE), intent(out) :: gamma0
real(kind=C_DOUBLE), intent(out) :: gamma1
real(kind=C_DOUBLE), intent(out) :: gamma2
real(kind=C_DOUBLE), intent(out) :: gamma3
real(kind=C_DOUBLE), intent(out) :: kappa0
real(kind=C_DOUBLE), intent(out) :: kappa1
real(kind=C_DOUBLE), intent(out) :: kappa2
real(kind=C_DOUBLE), intent(out) :: kappa3
real(kind=C_DOUBLE), intent(out) :: logP1
real(kind=C_DOUBLE), intent(out) :: logRho0
real(kind=C_DOUBLE), intent(out) :: logRho1
real(kind=C_DOUBLE), intent(out) :: logRho2
Description
Interface to the \(\texttt{LORENE}\) method of class \(\texttt{Et_diffrot}\) with the same name, that stores the physical parameters of the binary system from \(\texttt{LORENE}\) in the desired variables
FT 24.10.2021
Call graph
import_diffstar_params calls get_diffstar_params, import_diffstar_params
construct_diffstarlorene calls import_diffstar_params, construct_diffstarlorene
diffstarlorene calls construct_diffstarlorene
sphincs_lorene_bns calls diffstarlorene