get_fuka_id_params – SPHINCS_ID
get_fuka_id_params Interface
201 statements
Source File
interface
Called by
private subroutine get_fuka_id_params(optr, angular_vel, distance, mass1, mass2, massg1, massg2, radius1_min, radius1_max, radius2_min, radius2_max, adm_mass, komar_mass, adm_linear_momentum_x, adm_linear_momentum_y, adm_linear_momentum_z, adm_angular_momentum_z, COMx, COMy, COMz, area_radius1, center1_x, area_radius2, center2_x, ent_center1, rho_center1, energy_density_center1, ent_center2, rho_center2, energy_density_center2, eos_type, gamma, kappa, n_poly, gamma0, gamma1, gamma2, gamma3, kappa0, kappa1, kappa2, kappa3, logP1, logRho0, logRho1, logRho2) bind(C, NAME= "0")
Arguments
Type Intent Optional Attributes Name
type(C_PTR), intent(in), VALUE :: optr
C pointer pointing to a \(\texttt{FUKA}\) bns_export object
real(kind=C_DOUBLE), intent(out) :: angular_vel
real(kind=C_DOUBLE), intent(out) :: distance
real(kind=C_DOUBLE), intent(out) :: mass1
real(kind=C_DOUBLE), intent(out) :: mass2
real(kind=C_DOUBLE), intent(out) :: massg1
real(kind=C_DOUBLE), intent(out) :: massg2
real(kind=C_DOUBLE), intent(out) :: radius1_min
real(kind=C_DOUBLE), intent(out) :: radius1_max
real(kind=C_DOUBLE), intent(out) :: radius2_min
real(kind=C_DOUBLE), intent(out) :: radius2_max
real(kind=C_DOUBLE), intent(out) :: adm_mass
real(kind=C_DOUBLE), intent(out) :: komar_mass
real(kind=C_DOUBLE), intent(out) :: adm_linear_momentum_x
real(kind=C_DOUBLE), intent(out) :: adm_linear_momentum_y
real(kind=C_DOUBLE), intent(out) :: adm_linear_momentum_z
real(kind=C_DOUBLE), intent(out) :: adm_angular_momentum_z
real(kind=C_DOUBLE), intent(out) :: COMx
real(kind=C_DOUBLE), intent(out) :: COMy
real(kind=C_DOUBLE), intent(out) :: COMz
real(kind=C_DOUBLE), intent(out) :: area_radius1
real(kind=C_DOUBLE), intent(out) :: center1_x
real(kind=C_DOUBLE), intent(out) :: area_radius2
real(kind=C_DOUBLE), intent(out) :: center2_x
real(kind=C_DOUBLE), intent(out) :: ent_center1
real(kind=C_DOUBLE), intent(out) :: rho_center1
real(kind=C_DOUBLE), intent(out) :: energy_density_center1
real(kind=C_DOUBLE), intent(out) :: ent_center2
real(kind=C_DOUBLE), intent(out) :: rho_center2
real(kind=C_DOUBLE), intent(out) :: energy_density_center2
character(kind=C_CHAR), intent(out), DIMENSION(100) :: eos_type
real(kind=C_DOUBLE), intent(out) :: gamma
real(kind=C_DOUBLE), intent(out) :: kappa
integer(kind=C_INT), intent(out) :: n_poly
real(kind=C_DOUBLE), intent(out) :: gamma0
real(kind=C_DOUBLE), intent(out) :: gamma1
real(kind=C_DOUBLE), intent(out) :: gamma2
real(kind=C_DOUBLE), intent(out) :: gamma3
real(kind=C_DOUBLE), intent(out) :: kappa0
real(kind=C_DOUBLE), intent(out) :: kappa1
real(kind=C_DOUBLE), intent(out) :: kappa2
real(kind=C_DOUBLE), intent(out) :: kappa3
real(kind=C_DOUBLE), intent(out) :: logP1
real(kind=C_DOUBLE), intent(out) :: logRho0
real(kind=C_DOUBLE), intent(out) :: logRho1
real(kind=C_DOUBLE), intent(out) :: logRho2
Description
FT
Call graph
read_fuka_id_params calls get_fuka_id_params, read_fuka_id_params
construct_bnsfuka calls read_fuka_id_params, construct_bnsfuka