particles – SPHINCS_ID
particles Interface
4 statements
Source File
public interface particles
Interface of TYPE particles
Calls
Called by
Contents
Module Procedures
construct_particles_std construct_particles_bin
Module Procedures
public interface construct_particles_std()
Arguments
None
public interface construct_particles_bin()
Arguments
None
Call graph
particles calls construct_particles_std, construct_particles_bin
construct_particles_std calls construct_particles_std, read_options, impose_equatorial_plane_symmetry, spatial_vector_norm_sym3x3, spherical_from_cartesian, timer, correct_center_of_mass, set_units, check_particle_positions, alive, reflect_particles_yz_plane, allocate_particles_memory, shorten_eos_name, ktable
construct_particles_bin calls construct_particles_bin, read_options, allocate_sph_memory, omp_set_num_threads, compute_g4, select_eos_parameters, deallocate_sph_memory, spacetime_vector_norm_sym4x4, set_units, determinant_sym4x4
impose_equatorial_plane_symmetry calls impose_equatorial_plane_symmetry, com, reflect_particles_xy_plane, find_particles_above_xy_plane
correct_center_of_mass calls correct_center_of_mass, com
check_particle_positions calls check_particle_positions, indexx
allocate_particles_memory calls allocate_particles_memory
reflect_particles_xy_plane calls reflect_particles_xy_plane
find_particles_above_xy_plane calls find_particles_above_xy_plane
convergence_test calls particles
sphincs_id calls particles