read_fuka_id_spacetime – SPHINCS_ID
read_fuka_id_spacetime Interface
304 statements
Source File
interface
Calls
public module module subroutine read_fuka_id_spacetime(this, nx, ny, nz, pos, lapse, shift, g, ek) Implementation →
Arguments
Type Intent Optional Attributes Name
class(bnsfuka), intent(inout) :: this
bnsfuka object which this PROCEDURE is a member of
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: nz
double precision, intent(in), DIMENSION(:,:,:,:) :: pos
double precision, intent(inout), DIMENSION(:,:,:) :: lapse
double precision, intent(inout), DIMENSION(:,:,:,:) :: shift
double precision, intent(inout), DIMENSION(:,:,:,:) :: g
double precision, intent(inout), DIMENSION(:,:,:,:) :: ek
Description
Stores the spacetime \(\mathrm{ID}\) in multi-dimensional arrays needed to compute the BSSN variables and constraints
Call graph
read_fuka_id_spacetime calls read_fuka_id_spacetime, determinant_sym4x4, is_finite_number, get_fuka_id_spacetime, compute_g4, determinant_sym3x3